"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowRight,Check,CircleHelp,Cloud,CloudOff,FolderOpen,Gauge,HardDrive,Home,LoaderCircle,Mountain,Paperclip,Pencil,Plus,Route,ShieldCheck,TriangleAlert,WifiOff,Wrench,Backpack} from "lucide-react";
import {toast} from "sonner";
import {Toaster} from "@/components/ui/sonner";
import {Button} from "@/components/ui/button";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from "@/components/ui/dialog";
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from "@/components/ui/alert-dialog";
import {Skeleton} from "@/components/ui/skeleton";
import {EntityForm,titles,type EditableKind,type Editor} from "./forms";
import {MainViews,RideRow,FileListView,type Detail,type View,type ViewActions} from "./views";
import {StoragePanel} from "./storage-panel";
import {backup,entityKey,formatDate,formatKm,parseBackup,project,today,tripStats,validateDelete,validateEdit,type Attachment,type Conflict,type Entity,type Kind} from "@/lib/kairo/domain";
import {addAttachment,commit,copyLocalToAccount,friendlyError,loadWorkspace,mergeOperations,metaGet,metaSet,type Profile,type Workspace} from "@/lib/kairo/storage";
import {authorizeGoogle,cachedCloudStatus,prepareGoogle,readDriveConfig,type DriveClient,type DriveConfig} from "@/lib/kairo/drive";
import {exportWorkbook,readXlsx,workbookImport,writeXlsx,type ImportPreview} from "@/lib/kairo/excel";
import {appPath,LOCAL_CHANNEL} from "@/lib/kairo/paths";

const blank:Workspace={state:project([]),operations:[],pending:[],blobs:[]};
const nav=[{id:"overview",label:"Apžvalga",icon:Home},{id:"readings",label:"Odometras",icon:Gauge},{id:"rides",label:"Pasivažinėjimai",icon:Route},{id:"trips",label:"Kelionės",icon:Mountain},{id:"wheels",label:"Garažas",icon:Wrench},{id:"gear",label:"Ekipuotė",icon:Backpack}] as const;
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60_000);}
export default function KairoApp(){
  const [ready,setReady]=useState(false),[fatal,setFatal]=useState("");
  const [workspace,setWorkspace]=useState<Workspace>(blank),[profile,setProfile]=useState<Profile|null>(null);
  const namespace=useRef("local"),client=useRef<DriveClient|null>(null),syncing=useRef<DriveClient|null>(null),syncBlocked=useRef(false);
  const [online,setOnline]=useState(true),[connection,setConnection]=useState(false),[syncMessage,setSyncMessage]=useState("");
  const [cloud,setCloud]=useState<{rootId?:string;lastSync?:string}>({});
  const [view,setView]=useState<View>("overview"),[editor,setEditor]=useState<Editor|null>(null),[detail,setDetail]=useState<Detail|null>(null);
  const [driveOpen,setDriveOpen]=useState(false),[config,setConfig]=useState<DriveConfig|null>(null),[googleReady,setGoogleReady]=useState(false),[connecting,setConnecting]=useState(false);
  const [candidate,setCandidate]=useState<{client:DriveClient;profile:Profile;hasLocal:boolean}|null>(null);
  const [pendingDelete,setPendingDelete]=useState<{kind:Kind;entity:Entity;parents:string[];namespace:string}|null>(null);
  const [importPreview,setImportPreview]=useState<(ImportPreview&{namespace:string})|null>(null),[importBusy,setImportBusy]=useState(false),[importZone,setImportZone]=useState("Europe/Vilnius");
  const [conflict,setConflict]=useState<Conflict|null>(null),[persisted,setPersisted]=useState(false),[busy,setBusy]=useState(false),[offlineReady,setOfflineReady]=useState(false);
  const importInput=useRef<HTMLInputElement>(null),attachmentInput=useRef<HTMLInputElement>(null);
  const state=workspace.state;
  const refresh=useCallback(async()=>{const ns=namespace.current,next=await loadWorkspace(ns);if(ns===namespace.current)setWorkspace(next);},[]);
  useEffect(()=>{
    let mounted=true;
    void(async()=>{try{const active=await metaGet<Profile>("activeProfile");if(!mounted)return;if(active){namespace.current=active.namespace;setProfile(active);setCloud(await cachedCloudStatus(active.namespace));}await refresh();if(mounted){setReady(true);setPersisted(await navigator.storage?.persisted?.()??false);}}catch(e){if(mounted)setFatal(`Nepavyko atverti įrenginio saugyklos. ${friendlyError(e)}`);}})();
    const network=()=>{setOnline(navigator.onLine);if(navigator.onLine)syncBlocked.current=false;};network();window.addEventListener("online",network);window.addEventListener("offline",network);
    const channel=typeof BroadcastChannel!=="undefined"?new BroadcastChannel(LOCAL_CHANNEL):null;if(channel)channel.onmessage=e=>{if(e.data===namespace.current)void refresh().catch(e=>toast.error(friendlyError(e)));};
    const timer=setInterval(()=>setConnection(!!client.current?.connected),15000);
    const swMessage=(e:MessageEvent)=>{if(e.data?.type==="KAIRO_OFFLINE_READY")setOfflineReady(true);};
    if("serviceWorker"in navigator){navigator.serviceWorker.addEventListener("message",swMessage);void navigator.serviceWorker.register(appPath("sw.js"),{scope:appPath(),updateViaCache:"none"}).then(()=>navigator.serviceWorker.ready).then(reg=>reg.active?.postMessage({type:"CHECK_OFFLINE"})).catch(()=>{});}
    return()=>{mounted=false;window.removeEventListener("online",network);window.removeEventListener("offline",network);channel?.close();clearInterval(timer);navigator.serviceWorker?.removeEventListener("message",swMessage);client.current?.disconnect();};
  },[refresh]);
  useEffect(()=>{if(!driveOpen)return;let live=true;void readDriveConfig().then(async cfg=>{if(!live)return;setConfig(cfg);if(cfg.googleClientId){await prepareGoogle();if(live)setGoogleReady(true);}}).catch(e=>toast.error(friendlyError(e)));return()=>{live=false;};},[driveOpen]);
  useEffect(()=>{if(!ready||!online)return;let live=true;void readDriveConfig().then(async cfg=>{if(!live)return;setConfig(cfg);if(cfg.googleClientId){await prepareGoogle();if(live)setGoogleReady(true);}}).catch(()=>{});return()=>{live=false;};},[ready,online]);
  const runSync=useCallback(async()=>{
    const api=client.current,ns=namespace.current;if(!api||syncing.current===api||ns==="local")return;
    syncing.current=api;syncBlocked.current=false;setSyncMessage("Pradedamas sinchronizavimas…");
    try{const result=await api.sync(ns,s=>{if(namespace.current===ns&&client.current===api)setSyncMessage(s);});if(namespace.current===ns&&client.current===api){setCloud(result);await refresh();}}
    catch(e){if(client.current===api){syncBlocked.current=true;setConnection(api.connected);toast.error(friendlyError(e),{duration:8000});await refresh().catch(()=>{});}}
    finally{if(syncing.current===api)syncing.current=null;if(client.current===api)setSyncMessage("");}
  },[refresh]);
  useEffect(()=>{if(!connection||!online||!workspace.pending.length||syncing.current===client.current||syncBlocked.current)return;const timer=setTimeout(()=>void runSync(),1600);return()=>clearTimeout(timer);},[connection,online,workspace.pending.length,syncMessage,runSync]);
  const openEditor=(kind:EditableKind,entity?:Entity,tripId?:string)=>{setDetail(null);setEditor({kind,entity,tripId,namespace:namespace.current,parents:entity?(state.heads.get(entityKey(kind,entity.id))??[]).map(r=>r.operationId):[]});};
  const askDelete=(kind:Kind,entity:Entity)=>setPendingDelete({kind,entity,namespace:namespace.current,parents:(state.heads.get(entityKey(kind,entity.id))??[]).map(r=>r.operationId)});
  const actions:ViewActions={openEditor,askDelete,setDetail};
  async function save(value:Entity){if(!editor)return;const form=editor;setBusy(true);try{if(form.namespace!==namespace.current)throw new Error("Pasikeitė paskyra. Atverk įrašą iš naujo.");validateEdit((await loadWorkspace(form.namespace)).state,form.kind,value);await commit(form.namespace,form.kind,value,value.id,undefined,form.parents);syncBlocked.current=false;await refresh();setEditor(null);toast.success("Išsaugota šiame įrenginyje.");}catch(e){toast.error(friendlyError(e));}finally{setBusy(false);}}
  async function remove(){if(!pendingDelete)return;const t=pendingDelete;setBusy(true);try{if(t.namespace!==namespace.current)throw new Error("Pasikeitė paskyra.");validateDelete((await loadWorkspace(t.namespace)).state,t.kind,t.entity.id);const deletion=await commit(t.namespace,t.kind,null,t.entity.id,undefined,t.parents);await refresh();setPendingDelete(null);if(detail?.id===t.entity.id)setDetail(null);toast.success(t.kind==="attachment"?"Nuoroda pašalinta. Drive originalas liko.":"Įrašas pašalintas.",{action:{label:"Atšaukti",onClick:()=>{void commit(t.namespace,t.kind,t.entity,t.entity.id,undefined,[deletion.id]).then(refresh).catch(e=>toast.error(friendlyError(e)));}},duration:12000});}catch(e){toast.error(friendlyError(e));}finally{setBusy(false);}}
  async function activate(next:{client:DriveClient;profile:Profile},copy:boolean){
    setConnecting(true);
    try{
      if(copy)await copyLocalToAccount(next.profile);
      const [target,targetCloud]=await Promise.all([loadWorkspace(next.profile.namespace),cachedCloudStatus(next.profile.namespace)]);
      await metaSet("activeProfile",next.profile);
      client.current?.disconnect();client.current=next.client;namespace.current=next.profile.namespace;
      setWorkspace(target);setCloud(targetCloud);setProfile(next.profile);setConnection(next.client.connected);syncBlocked.current=false;
      setCandidate(null);setDetail(null);setEditor(null);setImportPreview(null);setConflict(null);setPendingDelete(null);setSyncMessage("");
      toast.success(`Prijungta ${next.profile.email}`);void runSync();
    }catch(e){next.client.disconnect();setCandidate(null);toast.error(friendlyError(e));}finally{setConnecting(false);}
  }
  function connect(){if(!config?.googleClientId||!googleReady||connecting)return;setConnecting(true);void authorizeGoogle(config.googleClientId,profile?.email).then(async api=>{try{const p=await api.about();if(namespace.current===p.namespace){await activate({client:api,profile:p},false);return;}const local=await loadWorkspace("local");if(namespace.current==="local"&&local.operations.length===0){await activate({client:api,profile:p},false);return;}setCandidate({client:api,profile:p,hasLocal:namespace.current==="local"&&local.operations.length>0});}catch(e){api.disconnect();throw e;}}).catch(e=>toast.error(friendlyError(e),{duration:8000})).finally(()=>setConnecting(false));}
  async function disconnect(){
    client.current?.disconnect();client.current=null;setConnection(false);setSyncMessage("");setWorkspace(blank);
    const local=await loadWorkspace("local");await metaSet("activeProfile",null);
    namespace.current="local";setWorkspace(local);setProfile(null);setCloud({});setDetail(null);setEditor(null);setImportPreview(null);setConflict(null);setPendingDelete(null);
    toast.info("Atsijungta. Paskyros vietinė kopija lieka atskirta ir bus pasiekiama grįžus į tą pačią paskyrą.");
  }
  async function readImport(file:File){const ns=namespace.current;setImportBusy(true);try{if(file.size>25*1024*1024)throw new Error("Importuojamo failo riba – 25 MB.");let preview:ImportPreview;if(file.name.toLowerCase().endsWith(".json")){const operations=parseBackup(JSON.parse(await file.text())),s=project(operations);preview={operations,warnings:["JSON kopijoje yra įrašai ir priedų nuorodos. Priedų originalai į JSON neįtraukti."],counts:{wheel:s.wheel.length,reading:s.reading.length,ride:s.ride.length,trip:s.trip.length,gear:s.gear.length,attachment:s.attachment.length},source:file.name};}else preview=await workbookImport(await readXlsx(new Uint8Array(await file.arrayBuffer())),importZone);setImportPreview({...preview,namespace:ns});}catch(e){toast.error(friendlyError(e),{duration:10000});}finally{setImportBusy(false);}}
  async function applyImport(){if(!importPreview)return;setImportBusy(true);try{if(importPreview.namespace!==namespace.current)throw new Error("Pasikeitė paskyra. Pasirink importo failą iš naujo.");await mergeOperations(namespace.current,importPreview.operations,false);syncBlocked.current=false;await refresh();setImportPreview(null);toast.success("Importas baigtas. Originalus failas nepakeistas.");}catch(e){toast.error(friendlyError(e));}finally{setImportBusy(false);}}
  function exportData(format:"json"|"xlsx"){try{if(format==="json")download(new Blob([JSON.stringify(backup(workspace.operations),null,2)],{type:"application/json"}),`Kairo-Ride-${today()}.json`);else download(new Blob([writeXlsx(exportWorkbook(workspace.operations)) as BlobPart],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),`Kairo-Ride-${today()}.xlsx`);toast.success("Eksportas paruoštas. Priedų originalai į jį neįtraukti.");}catch(e){toast.error(friendlyError(e));}}
  async function attach(files:FileList|null){if(!files||!detail)return;const owner={...detail},ns=namespace.current;setBusy(true);let count=0;try{for(const file of Array.from(files)){await addAttachment(ns,owner.kind,owner.id,file);count++;}syncBlocked.current=false;toast.success(`Išsaugota failų šiame įrenginyje: ${count}.`);}catch(e){toast.error(`${count?`Išsaugota ${count}. `:""}${friendlyError(e)}`,{duration:9000});}finally{await refresh();setBusy(false);}}
  function localDownload(a:Attachment){const b=workspace.blobs.find(b=>b.attachmentId===a.id);if(b)download(b.blob,a.name);else toast.info("Originalo šiame įrenginyje nėra. Atverk jį Drive.");}
  async function resolveRevision(value:Entity|null){if(!conflict)return;setBusy(true);try{await commit(namespace.current,conflict.kind,value,conflict.entityId,undefined,conflict.revisions.map(r=>r.operationId));await refresh();setConflict(null);toast.success("Pasirinkta versija išsaugota. Abi ankstesnės versijos lieka istorijoje.");}catch(e){toast.error(friendlyError(e));}finally{setBusy(false);}}
  async function persist(){try{const value=await navigator.storage?.persist?.();setPersisted(!!value);toast.info(value?"Naršyklė suteikė patvaresnę vietinę saugyklą.":"Naršyklė leidimo nesuteikė. Reguliariai eksportuok kopiją.");}catch(e){toast.error(friendlyError(e));}}
  const pendingFiles=state.attachment.filter(a=>!a.driveId).length;
  const syncLabel=syncMessage?"Sinchronizuojama":!online?"Be interneto":!profile?googleReady?"Prijungti Drive":"Šiame įrenginyje":!connection?"Atnaujinti prieigą":workspace.pending.length||pendingFiles?"Laukia įkėlimo":"Drive prijungtas";
  const activeTrip=detail?.kind==="trip"?state.trip.find(t=>t.id===detail.id):undefined,activeRide=detail?.kind==="ride"?state.ride.find(r=>r.id===detail.id):undefined;
  const tripInfo=activeTrip?tripStats(activeTrip,state.ride,state.attachment):undefined;
  const files=detail?state.attachment.filter(a=>a.ownerKind===detail.kind&&a.ownerId===detail.id):[],localIds=new Set(workspace.blobs.map(b=>b.attachmentId));
  const fileList=(items:Attachment[])=><FileListView files={items} localIds={localIds} onDownload={localDownload} onDelete={a=>askDelete("attachment",a)}/>;
  if(fatal)return <main className="startup"><TriangleAlert/><h1>Kairo Ride</h1><p role="alert">{fatal}</p><Button onClick={()=>location.reload()}>Bandyti dar kartą</Button><p>Privačioje naršymo sesijoje saugykla gali būti ribojama. Nieko neištrynėme.</p></main>;
  if(!ready)return <main className="startup"><div className="brand"><span className="brand-mark"><Route/></span>Kairo Ride</div><p>Atveriami šio įrenginio įrašai…</p><Skeleton className="h-24 w-80"/><noscript>Programėlei būtinas JavaScript. Asmeniniai duomenys saugomi įrenginyje ir tavo Google Drive.</noscript></main>;
  return <div className="kairo-app"><Toaster position="top-center" richColors theme="dark"/><a className="skip-link" href="#main-content">Pereiti prie turinio</a>
    <header className="app-header"><button className="brand" onClick={()=>setView("overview")} aria-label="Kairo Ride apžvalga"><span className="brand-mark"><Route strokeWidth={2.4}/></span><span>Kairo <b>Ride</b></span></button><div className="header-right"><span className="milestone">Pirmas etapas</span><Button variant="outline" className={`sync-button ${!profile?"local":""}`} disabled={connecting} onClick={()=>googleReady&&online&&!connection?connect():setDriveOpen(true)}>{syncMessage||connecting?<LoaderCircle className="spin"/>:!online?<WifiOff/>:connection?<Cloud/>:<HardDrive/>}<span>{syncLabel}</span>{workspace.pending.length>0&&<span className="count-badge">{workspace.pending.length}</span>}</Button></div></header>
    <Tabs value={view} onValueChange={v=>setView(v as View)} className="app-tabs"><div className="navigation"><TabsList variant="line" className="main-tabs" aria-label="Pagrindinės sritys">{nav.map(n=><TabsTrigger value={n.id} key={n.id} aria-label={n.label} title={n.label}><n.icon/><span className={n.id==="rides"?"wide-nav-label":undefined}>{n.label}</span>{n.id==="rides"&&<span className="compact-nav-label" aria-hidden="true">Važiavimai</span>}</TabsTrigger>)}</TabsList><span className="nav-caption">Tavo kelias. Tavo archyvas.</span></div><main id="main-content" className="app-main">
      {!profile&&<div className="local-notice"><HardDrive/><p><strong>Kol kas saugoma tik šiame įrenginyje.</strong> Kitame įrenginyje įrašus matysi tik prijungęs Drive. Iki tol naudok eksportą.</p><Button variant="ghost" size="sm" onClick={()=>setDriveOpen(true)}>Saugojimas <ArrowRight/></Button></div>}
      {!online&&<div className="notice"><WifiOff/><span>Gali tęsti be interneto. Pakeitimai pasieks kitą įrenginį tik po įkėlimo į Drive.</span></div>}
      {state.conflicts.length>0&&<div className="notice warning"><TriangleAlert/><span>{state.conflicts.length} įrašų versijos nesutampa. Rodoma laikina versija; abi išsaugotos.</span><Button variant="outline" size="sm" onClick={()=>setConflict(state.conflicts[0])}>Peržiūrėti</Button></div>}
      {state.integrity.length>0&&<div className="notice warning"><TriangleAlert/><span>{state.integrity.join(" ")} Atkurk trūkstamą istoriją iš JSON kopijos.</span></div>}
      <MainViews state={state} actions={actions} setView={setView} openStorage={()=>setDriveOpen(true)}/>
    </main></Tabs><footer className="app-footer"><span>Kairo Ride <small>2.0.1</small></span><span><ShieldCheck/>Be reklamos ir analitikos. Duomenys – tavo.</span><Button variant="ghost" size="sm" onClick={()=>setDriveOpen(true)}><CircleHelp/>Duomenys ir saugojimas</Button></footer>

    <Dialog open={!!editor} onOpenChange={open=>{if(!open&&!busy)setEditor(null);}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{editor?.entity?"Redaguoti":"Naujas įrašas"}: {editor&&titles[editor.kind].toLowerCase()}</DialogTitle><DialogDescription>{editor?.kind==="reading"?"Įrašyk visą odometro reikšmę, ne pasivažinėjimo atstumą.":editor?.kind==="trip"?"Kelionę sudaro datos, pasivažinėjimai ir bendri priedai.":"Pakeitimai bus išsaugoti tik paspaudus išsaugojimo mygtuką."}</DialogDescription></DialogHeader>{editor&&<EntityForm key={`${editor.kind}:${editor.entity?.id??"new"}`} editor={editor} state={state} busy={busy} onSave={save} onCancel={()=>setEditor(null)}/>}</DialogContent></Dialog>

    <Dialog open={!!detail} onOpenChange={open=>{if(!open&&!busy)setDetail(null);}}><DialogContent className="detail-dialog"><DialogHeader><div className="eyebrow">{activeTrip?"KELIONĖ":"PASIVAŽINĖJIMAS"}</div><DialogTitle className="detail-title">{activeTrip?.name??activeRide?.name??"Įrašas nepasiekiamas"}</DialogTitle><DialogDescription>{activeTrip?`${formatDate(activeTrip.startDate)} → ${formatDate(activeTrip.endDate)} · ${tripInfo?.days} d.`:activeRide?`${formatDate(activeRide.at,true,activeRide.timeZone)} · ${state.wheel.find(w=>w.id===activeRide.wheelId)?.name??""}`:"Įrašas galėjo būti pašalintas kitame įrenginyje."}</DialogDescription></DialogHeader>
      {(activeTrip||activeRide)&&<><div className="detail-meta"><span><Route/>{formatKm(tripInfo?tripInfo.distanceKm:activeRide?.distanceKm??null)} km{tripInfo?.unknownDistances?" + neįvesti atstumai":""}</span><span><Paperclip/>{tripInfo?tripInfo.attachments.length:files.length} priedų</span><Button variant="ghost" size="sm" onClick={()=>openEditor(activeTrip?"trip":"ride",activeTrip??activeRide!)}><Pencil/>Redaguoti</Button></div>{(activeTrip?.notes||activeRide?.notes)&&<p className="detail-notes preserve-lines">{activeTrip?.notes||activeRide?.notes}</p>}
      {activeTrip&&<section className="detail-section"><div className="section-heading"><h3>Kelionės pasivažinėjimai</h3><Button variant="outline" size="sm" disabled={!state.wheel.length} onClick={()=>openEditor("ride",undefined,activeTrip.id)}><Plus/>Pridėti</Button></div>{tripInfo?.rides.length?tripInfo.rides.map(r=><RideRow key={r.id} ride={r} state={state} actions={actions}/>):<p className="muted">Dar nepriskirta. Esamą pasivažinėjimą gali priskirti redaguodamas jo lauką „Kelionė“.</p>}{!state.wheel.length&&<p className="field-hint">Kad pridėtum pasivažinėjimą, pirmiausia pridėk vienaratį garaže.</p>}</section>}
      {activeRide?.tripId&&<Button variant="outline" onClick={()=>setDetail({kind:"trip",id:activeRide.tripId!})}><Mountain/>Atverti kelionę</Button>}
      <section className="detail-section"><div className="section-heading"><h3>{activeTrip?"Bendri kelionės failai":"Pasivažinėjimo failai"}</h3><Button variant="outline" size="sm" disabled={busy} onClick={()=>attachmentInput.current?.click()}>{busy?<LoaderCircle className="spin"/>:<Paperclip/>}Prisegti</Button></div><p className="field-hint">GPX, CSV logai, nuotraukos, video ir kiti originalai. Iki 512 MB vienam failui. Turinys nekeičiamas ir neanalizuojamas.</p>{files.length?fileList(files):<div className="attachment-empty"><FolderOpen/><span>Prisek pirmą failą. Jis bus susietas su šiuo įrašu.</span></div>}{!connection&&<p className="inline-warning"><CloudOff/>Kol Drive neprijungtas, failai bus tik šiame įrenginyje.</p>}</section>
      {activeTrip&&!!tripInfo?.attachments.filter(a=>a.ownerKind==="ride").length&&<section className="detail-section"><h3>Pasivažinėjimų priedai</h3>{fileList(tripInfo.attachments.filter(a=>a.ownerKind==="ride"))}</section>}</>}
    </DialogContent></Dialog><input ref={attachmentInput} type="file" multiple className="sr-only" tabIndex={-1} aria-label="Prisegti failus" onChange={e=>{void attach(e.target.files);e.target.value="";}}/>

    <StoragePanel open={driveOpen} setOpen={setDriveOpen} config={config} profile={profile} connection={connection} connecting={connecting} googleReady={googleReady} online={online} syncMessage={syncMessage} cloud={cloud} pending={workspace.pending.length} pendingFiles={pendingFiles} importZone={importZone} setImportZone={setImportZone} importBusy={importBusy} offlineReady={offlineReady} persisted={persisted} onConnect={connect} onSync={()=>void runSync()} onDisconnect={()=>void disconnect().catch(e=>toast.error(friendlyError(e)))} onImport={()=>importInput.current?.click()} onExport={exportData} onPersist={()=>void persist()}/><input ref={importInput} type="file" accept=".json,.xlsx" className="sr-only" tabIndex={-1} aria-label="Importuoti duomenis" onChange={e=>{if(e.target.files?.[0])void readImport(e.target.files[0]);e.target.value="";}}/>

    <AlertDialog open={!!candidate} onOpenChange={open=>{if(!open&&!connecting){candidate?.client.disconnect();setCandidate(null);}}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Prijungti {candidate?.profile.email}?</AlertDialogTitle><AlertDialogDescription>{candidate?.hasLocal?"Šiame įrenginyje jau yra vietinių įrašų ir failų. Ar nukopijuoti juos į šią paskyrą? Vietinė originali kopija nebus ištrinta.":"Bus atverta šios paskyros duomenų erdvė. Ankstesnės paskyros įrašai į ją automatiškai neperkeliami."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={connecting}>Atšaukti</AlertDialogCancel>{candidate?.hasLocal&&<Button variant="outline" disabled={connecting} onClick={()=>candidate&&void activate(candidate,false)}>Be vietinių įrašų</Button>}<Button disabled={connecting} onClick={()=>candidate&&void activate(candidate,!!candidate.hasLocal)}>{connecting?<LoaderCircle className="spin"/>:<Check/>}{candidate?.hasLocal?"Kopijuoti ir prijungti":"Prijungti paskyrą"}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={!!pendingDelete} onOpenChange={open=>{if(!open&&!busy)setPendingDelete(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Pašalinti įrašą?</AlertDialogTitle><AlertDialogDescription>{pendingDelete?.kind==="attachment"?"Pašalinsime tik priedo ryšį su įrašu. Originalaus Drive failo netrinsime.":"Pašalinimas bus įtrauktas į istoriją. Iškart po veiksmo galėsi jį atšaukti."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Palikti</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={busy} onClick={e=>{e.preventDefault();void remove();}}>Pašalinti</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={!!importPreview} onOpenChange={open=>{if(!open&&!importBusy)setImportPreview(null);}}><DialogContent className="import-dialog"><DialogHeader><DialogTitle>Importo peržiūra</DialogTitle><DialogDescription>{importPreview?.source}. Dar nieko neįrašyta.</DialogDescription></DialogHeader>{importPreview&&<><div className="import-counts"><span><strong>{importPreview.counts.wheel}</strong>vienaračių</span><span><strong>{importPreview.counts.reading}</strong>rodmenų</span><span><strong>{importPreview.counts.ride}</strong>pasivažinėjimų</span><span><strong>{importPreview.counts.trip}</strong>kelionių</span><span><strong>{importPreview.counts.gear}</strong>ekipuotės</span></div><ul className="import-warnings">{importPreview.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul><p className="field-hint">Įrašai sujungiami pagal stabilius ID. Pakartotinis to paties failo importas jų nedaugina. Skirtingos to paties įrašo versijos parodomos kaip konfliktas.</p></>}<DialogFooter><Button variant="outline" disabled={importBusy} onClick={()=>setImportPreview(null)}>Atšaukti</Button><Button disabled={importBusy} onClick={()=>void applyImport()}>{importBusy?<LoaderCircle className="spin"/>:<Check/>}Patvirtinti importą</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!conflict} onOpenChange={open=>{if(!open&&!busy)setConflict(null);}}><DialogContent className="conflict-dialog"><DialogHeader><DialogTitle>Pasirink, kurią versiją palikti</DialogTitle><DialogDescription>Skirtingi įrenginiai pakeitė tą patį įrašą. Nieko tyliai neperrašėme. Pasirinkimas išsprendžia tik šį konfliktą.</DialogDescription></DialogHeader>{conflict?.revisions.map((r,i)=><div className="conflict-version" key={r.operationId}><strong>Versija {i+1} · {formatDate(r.createdAt,true)}</strong><pre>{r.value?JSON.stringify(r.value,null,2):"Įrašas pašalintas"}</pre><Button disabled={busy} onClick={()=>void resolveRevision(r.value)}>Palikti šią versiją</Button></div>)}</DialogContent></Dialog>
  </div>;
}
