"use client";
import {useEffect,useState} from "react";
import {Activity,Check,Clipboard,Download,Mail,Play,ShieldAlert,Trash2} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {clearDiagnosticLog,detailedDiagnosticsUntil,diagnosticReport,diagnosticText,disableDetailedDiagnostics,enableDetailedDiagnostics,loadDiagnosticLog,recordDiagnostic,runHealthCheck,shareDiagnosticReport,type DiagnosticEvent,type HealthReport} from "@/lib/kairo/diagnostics";
import {formatDate} from "@/lib/kairo/domain";
import {useI18n} from "@/lib/kairo/i18n";

type Props={active:boolean;namespace:string;connected:boolean;account?:string;pendingRecords:number;pendingFiles:number;conflicts:number;lastSync?:string};
function saveText(text:string,name:string){const blob=new Blob([text],{type:"text/plain"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60_000);}
export function DiagnosticsPanel(p:Props){
  const {tr,locale}=useI18n(),[events,setEvents]=useState<DiagnosticEvent[]>([]),[health,setHealth]=useState<HealthReport|null>(null),[busy,setBusy]=useState(false),[report,setReport]=useState<Record<string,unknown>|null>(null),[detailedUntil,setDetailedUntil]=useState(detailedDiagnosticsUntil);
  const reload=async()=>setEvents(await loadDiagnosticLog(p.namespace));
  useEffect(()=>{if(!p.active)return;let live=true;void loadDiagnosticLog(p.namespace).then(rows=>{if(live)setEvents(rows);});return()=>{live=false;};},[p.active,p.namespace]);
  useEffect(()=>{if(!detailedUntil)return;const delay=Math.max(0,detailedUntil-Date.now()),timer=setTimeout(()=>setDetailedUntil(0),delay);return()=>clearTimeout(timer);},[detailedUntil]);
  async function check(){setBusy(true);try{const value=await runHealthCheck(p.namespace,p);setHealth(value);await recordDiagnostic(p.namespace,value.database.status==="ok"?"info":"error","DIAGNOSTICS.SELF_CHECK",{module:"diagnostics",action:"self-check",message:value.database.status==="ok"?"Application self-check completed.":"Application self-check found a database problem.",technical:value});await reload();toast.success(value.database.status==="ok"?tr("Self-check completed.","Savikontrolė baigta."):tr("Self-check found a problem. Review the report.","Savikontrolė rado problemą. Peržiūrėk ataskaitą."));}catch(error){toast.error(error instanceof Error?error.message:String(error));}finally{setBusy(false);}}
  async function openReport(){setBusy(true);try{const current=health??await runHealthCheck(p.namespace,p);setHealth(current);setReport(await diagnosticReport(p.namespace,current));}catch(error){toast.error(error instanceof Error?error.message:String(error));}finally{setBusy(false);}}
  async function share(){if(!report)return;try{const result=await shareDiagnosticReport(report);toast.info(result==="shared"?tr("The system share action completed. Confirm the recipient and send it to kairosbytomas@gmail.com; Kairo Ride cannot verify email delivery.","Sistemos bendrinimo veiksmas baigtas. Patvirtink gavėją ir išsiųsk į kairosbytomas@gmail.com; Kairo Ride negali patikrinti laiško pristatymo."):tr("The report was downloaded and an email draft was opened. Attach the downloaded report before sending.","Ataskaita atsisiųsta ir atvertas laiško juodraštis. Prieš siunčiant pridėk atsisiųstą ataskaitą."),{duration:10000});}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError"))toast.error(error instanceof Error?error.message:String(error));}}
  const statuses=health?[health.app.status,health.database.status,health.drive.status,health.synchronization.status,health.storage.status,health.serviceWorker.status]:[];
  return <section className="storage-section diagnostics-section"><div className="diagnostics-heading"><div><h3><Activity/>{tr("Diagnostics","Diagnostika")}</h3><p>{tr("Local, privacy-safe stability and error information for the entire app.","Vietinė, privatumą sauganti visos programos stabilumo ir klaidų informacija.")}</p></div><Button variant="outline" disabled={busy} onClick={()=>void check()}><Play/>{tr("Run self-check","Paleisti savikontrolę")}</Button></div>
    <p className="field-hint">{tr("No telemetry is sent automatically. Reports exclude access tokens, authorization headers, upload session URLs, full Drive IDs, the database and original media.","Telemetrija automatiškai nesiunčiama. Ataskaitose nėra prieigos žetonų, autorizacijos antraščių, įkėlimo sesijų adresų, pilnų Drive ID, duomenų bazės ar originalių failų.")}</p>
    <label className="auto-sync-setting compact"><input type="checkbox" checked={detailedUntil>0} onChange={event=>{if(event.target.checked)setDetailedUntil(enableDetailedDiagnostics(30));else{disableDetailedDiagnostics();setDetailedUntil(0);}}}/><span><strong>{tr("Detailed diagnostic session (30 minutes)","Detali diagnostikos sesija (30 min.)")}</strong><small>{tr("Adds sanitized before/after context to new events. It turns off automatically.","Prie naujų įvykių prideda išvalytą kontekstą prieš ir po. Išsijungia automatiškai.")}</small></span></label>
    {health&&<div className="health-grid">{[["App",health.app.status],[tr("Database","Duomenų bazė"),health.database.status],["Google Drive",health.drive.status],[tr("Sync","Sinchronizavimas"),health.synchronization.status],[tr("Storage","Saugykla"),health.storage.status],[tr("App cache","Programos talpykla"),health.serviceWorker.status]].map(([label,status])=><div className={`health-${status}`} key={label}><span>{status==="ok"?<Check/>:<ShieldAlert/>}{label}</span><strong>{status}</strong></div>)}</div>}
    <div className="diagnostic-actions"><Button onClick={()=>void openReport()} disabled={busy}>{tr("Create report","Sukurti ataskaitą")}</Button><Button variant="outline" disabled={!events.length} onClick={()=>{const latest=events[0];void navigator.clipboard?.writeText(JSON.stringify(latest,null,2));toast.info(tr("Latest event copied.","Naujausias įvykis nukopijuotas."));}}><Clipboard/>{tr("Copy latest","Kopijuoti naujausią")}</Button><Button variant="ghost" disabled={!events.length} onClick={()=>{if(confirm(tr("Clear the local diagnostic log? This does not affect your records.","Išvalyti vietinį diagnostikos žurnalą? Įrašai nebus paveikti.")))void clearDiagnosticLog(p.namespace).then(reload);}}><Trash2/>{tr("Clear log","Išvalyti žurnalą")}</Button></div>
    <div className="diagnostic-log">{events.length?events.map(event=><details key={event.key} className={`diagnostic-event diagnostic-${event.level}`}><summary><span>{event.level}</span><strong>{event.code}</strong><small>{formatDate(event.createdAt,true,undefined,locale)}</small></summary><div><p>{event.message}</p><dl><div><dt>{tr("Incident","Incidentas")}</dt><dd>{event.incidentId}</dd></div>{event.module&&<div><dt>{tr("Module","Modulis")}</dt><dd>{event.module}</dd></div>}{event.action&&<div><dt>{tr("Action","Veiksmas")}</dt><dd>{event.action}</dd></div>}{event.source&&<div><dt>{tr("Source","Šaltinis")}</dt><dd>{event.source}</dd></div>}</dl>{event.stack&&<pre>{event.stack}</pre>}</div></details>):<p className="field-hint">{tr("No diagnostic events are stored yet.","Diagnostikos įvykių dar nėra.")}</p>}</div>
    {health&&statuses.includes("error")&&<p className="inline-warning"><ShieldAlert/>{tr("A critical self-check failed. Export a JSON data backup before making more changes.","Kritinė savikontrolė nepavyko. Prieš tęsiant eksportuok JSON duomenų kopiją.")}</p>}
    {report&&<Dialog open onOpenChange={open=>{if(!open)setReport(null);}}><DialogContent className="diagnostic-report-dialog"><DialogHeader><DialogTitle>{tr("Diagnostic report preview","Diagnostikos ataskaitos peržiūra")}</DialogTitle><DialogDescription>{tr("Review exactly what will be shared. Sending is always your explicit action.","Peržiūrėk, kas tiksliai bus bendrinama. Siuntimas visada atliekamas tik tavo veiksmu.")}</DialogDescription></DialogHeader><pre>{diagnosticText(report)}</pre><DialogFooter><Button variant="outline" onClick={()=>setReport(null)}>{tr("Close","Uždaryti")}</Button><Button variant="outline" onClick={()=>saveText(diagnosticText(report),`Kairo-Ride-diagnostics-${Date.now()}.txt`)}><Download/>{tr("Download","Atsisiųsti")}</Button><Button onClick={()=>void share()}><Mail/>{tr("Send report to developer","Siųsti ataskaitą kūrėjui")}</Button></DialogFooter></DialogContent></Dialog>}
  </section>;
}
