"use client";
import {useEffect,useState} from "react";
import {ArrowDownToLine,ArrowUpFromLine,Bell,Check,CheckCheck,Cloud,FolderOpen,HardDrive,Languages,LoaderCircle,Mail,RefreshCw,RotateCcw,ShieldCheck,Smartphone} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {Field,Pick} from "./forms";
import {NUMBER_FORMATS,formatNumber,type NumberFormat} from "@/lib/kairo/numbers";
import {formatDate,type Attachment} from "@/lib/kairo/domain";
import {driveFolderUrl,type DriveConfig} from "@/lib/kairo/drive";
import type {Profile,RecoverySnapshot,StoredBlob} from "@/lib/kairo/storage";
import {appPath} from "@/lib/kairo/paths";
import {useI18n} from "@/lib/kairo/i18n";
import {DATE_FORMATS,formatDateKey,type DateFormat,type WeekStart} from "@/lib/kairo/calendar";
import {TransferCenter,type LiveTransfer} from "./transfer-center";
import {DiagnosticsPanel} from "./diagnostics-panel";
import type {AppUpdate} from "@/hooks/use-app-update";
import {APP_VERSION} from "@/lib/kairo/version";

type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
export type SettingsSection="appearance"|"sync"|"transfer"|"diagnostics"|"info";
type Props={
  open:boolean;setOpen:(value:boolean)=>void;initialSection?:SettingsSection;namespace:string;
  config:DriveConfig|null;profile:Profile|null;connection:boolean;connecting:boolean;googleReady:boolean;online:boolean;
  autoSyncEnabled:boolean;onAutoSyncChange:(enabled:boolean)=>void;syncIssue:{message:string;retry:boolean}|null;syncMessage:string;
  cloud:{rootId?:string;lastSync?:string};pending:number;pendingFiles:number;conflicts:number;
  attachments:Attachment[];blobs:StoredBlob[];liveTransfers:Record<string,LiveTransfer>;onTransferChanged:()=>Promise<void>;
  wakeLock:boolean;wakeLockSupported:boolean;onWakeLockChange:(value:boolean)=>void;
  recoverySnapshots:RecoverySnapshot[];onRestoreSnapshot:(snapshot:RecoverySnapshot)=>Promise<void>;
  importZone:string;setImportZone:(value:string)=>void;importBusy:boolean;offlineReady:boolean;persisted:boolean;notificationsEnabled:boolean;
  update:AppUpdate|null;updateChecking:boolean;updateActivating:boolean;updateError:string;onCheckUpdate:()=>void;onApplyUpdate:()=>void;
  onEnableNotifications:()=>void;onDisableNotifications:()=>void;onConnect:()=>void;onSync:()=>void;onDisconnect:()=>void;
  onImport:()=>void;onExport:(format:"json"|"xlsx")=>void;onPersist:()=>void;
};

export function StoragePanel(p:Props){
  const {tr,locale,language,setLanguage,dateFormat,weekStartsOn,setCalendar,numberFormat,setNumberFormat}=useI18n();
  const initialDraft=()=>({language,dateFormat,weekStartsOn,numberFormat,auto:p.autoSyncEnabled,notifications:p.notificationsEnabled,zone:p.importZone});
  const [draft,setDraft]=useState(initialDraft),[section,setSection]=useState<SettingsSection>(p.initialSection??"appearance");
  const dirty=draft.numberFormat!==numberFormat||draft.language!==language||draft.dateFormat!==dateFormat||draft.weekStartsOn!==weekStartsOn||draft.auto!==p.autoSyncEnabled||draft.notifications!==p.notificationsEnabled||draft.zone!==p.importZone;
  const cancel=()=>{if(!dirty||window.confirm(tr("Discard unapplied settings?","Atmesti nepritaikytus nustatymus?")))p.setOpen(false);};
  function apply(){setNumberFormat(draft.numberFormat);setLanguage(draft.language);setCalendar({dateFormat:draft.dateFormat,weekStartsOn:draft.weekStartsOn});p.onAutoSyncChange(draft.auto);p.setImportZone(draft.zone);if(draft.notifications!==p.notificationsEnabled){if(draft.notifications)p.onEnableNotifications();else p.onDisableNotifications();}p.setOpen(false);}
  const [installPrompt,setInstallPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(false),[installing,setInstalling]=useState(false);
  useEffect(()=>{
    const media=window.matchMedia("(display-mode: standalone)"),update=()=>setInstalled(media.matches||(navigator as Navigator&{standalone?:boolean}).standalone===true);
    const available=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPrompt);},done=()=>{setInstallPrompt(null);setInstalled(true);};
    update();media.addEventListener("change",update);window.addEventListener("beforeinstallprompt",available);window.addEventListener("appinstalled",done);
    return()=>{media.removeEventListener("change",update);window.removeEventListener("beforeinstallprompt",available);window.removeEventListener("appinstalled",done);};
  },[]);
  async function install(){if(!installPrompt||installing)return;setInstalling(true);try{await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);}catch{toast.info(tr("Use the browser menu and the steps below to install the app.","Naudok naršyklės meniu ir žemiau pateiktus žingsnius."));}finally{setInstalling(false);}}
  const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  const sections=[{value:"appearance",label:tr("Appearance & regional settings","Išvaizda ir regioniniai nustatymai")},{value:"sync",label:tr("Synchronization","Sinchronizavimas")},{value:"transfer",label:"Import / Export"},{value:"diagnostics",label:tr("Diagnostics","Diagnostika")},{value:"info",label:tr("Information","Informacija")}];
  return <Dialog open={p.open} onOpenChange={open=>{if(!open)cancel();}}><DialogContent className="storage-dialog settings-page" showCloseButton={false}>
    <DialogHeader><div className="settings-title-row"><DialogTitle>{tr("Settings","Nustatymai")}</DialogTitle><Pick label={tr("Settings sections","Nustatymų grupės")} value={section} onChange={value=>setSection(value as SettingsSection)} options={sections}/></div><DialogDescription>{tr("Language, synchronization, transfers, recovery and diagnostics in one place.","Kalba, sinchronizavimas, failų perdavimai, atkūrimas ir diagnostika vienoje vietoje.")}</DialogDescription></DialogHeader>
    <div className="settings-body">
      <div hidden={section!=="appearance"}>
        <section className="storage-section settings-section"><h3><Languages/>{tr("Language","Kalba")}</h3><p>{tr("The preference is stored on this device. English remains the default for new installations.","Pasirinkimas saugomas šiame įrenginyje. Naujuose diegimuose numatytoji kalba lieka anglų.")}</p><div className="language-options"><button className={draft.language==="en"?"active":""} onClick={()=>setDraft({...draft,language:"en"})}><span>English</span><small>Default</small>{draft.language==="en"&&<Check/>}</button><button className={draft.language==="lt"?"active":""} onClick={()=>setDraft({...draft,language:"lt"})}><span>Lietuvių</span><small>Optional</small>{draft.language==="lt"&&<Check/>}</button></div></section>
        <section className="storage-section settings-section"><h3>{tr("Number format","Skaičių formatas")}</h3><Field label={tr("Number format","Skaičių formatas")}><Pick label={tr("Number format","Skaičių formatas")} value={draft.numberFormat} onChange={value=>setDraft({...draft,numberFormat:value as NumberFormat})} options={NUMBER_FORMATS.map(value=>({value,label:formatNumber(1234567.89,{},value)}))}/></Field></section>
        <section className="storage-section settings-section"><h3>{tr("Dates & calendar","Datos ir kalendorius")}</h3><div className="form-grid"><Field label={tr("Date format","Datos formatas")}><Pick label={tr("Date format","Datos formatas")} value={draft.dateFormat} onChange={value=>setDraft({...draft,dateFormat:value as DateFormat})} options={DATE_FORMATS.map(value=>({value,label:`${value} · ${formatDateKey("2026-08-30",value)}`}))}/></Field><Field label={tr("Week starts on","Savaitės pradžia")}><Pick label={tr("Week starts on","Savaitės pradžia")} value={String(draft.weekStartsOn)} onChange={value=>setDraft({...draft,weekStartsOn:Number(value) as WeekStart})} options={Array.from({length:7},(_,day)=>({value:String(day),label:new Intl.DateTimeFormat(locale,{weekday:"long",timeZone:"UTC"}).format(new Date(Date.UTC(2024,0,7+day)))}))}/></Field></div><p className="field-hint">{tr("Defaults: yyyy/mm/dd and Monday. Stored timestamps and exports keep an unambiguous machine format.","Numatyta: yyyy/mm/dd ir pirmadienis. Saugojimo bei eksporto laiko žymos lieka vienareikšmio kompiuterinio formato.")}</p></section>
        <section className="storage-section settings-section"><h3><Bell/>{tr("Maintenance reminders","Priežiūros priminimai")}</h3><p>{tr("Kairo Ride checks maintenance while the PWA is open or active. A fully closed mobile PWA cannot guarantee scheduled notifications without a server.","Kairo Ride tikrina priežiūrą, kai PWA atidaryta arba aktyvi. Visiškai uždaryta mobilioji PWA be serverio negali garantuoti suplanuotų pranešimų.")}</p>{draft.notifications?<Button variant="outline" onClick={()=>setDraft({...draft,notifications:false})}>{tr("Disable local reminders","Išjungti vietinius priminimus")}</Button>:<Button onClick={()=>setDraft({...draft,notifications:true})}><Bell/>{tr("Enable local reminders","Įjungti vietinius priminimus")}</Button>}<p className="field-hint">{tr("Active! popups in Garage and when adding a record always appear when a reminder applies. They do not require notification permission.","Aktyvus! priminimai Garaže ir pridedant įrašą rodomi visada, kai aktualūs. Jiems nereikia pranešimų leidimo.")}</p></section>
      </div>
      <div hidden={section!=="sync"}>
        <section className="drive-box"><div className="drive-heading"><span className="drive-icon"><Cloud/></span><div><h3>Google Drive</h3><p>{p.profile?.email??tr("Your private Kairo Ride folder","Tavo asmeninis Kairo Ride aplankas")}</p></div>{p.connection&&<span className="connected-dot"/>}</div>
          {p.config&&!p.config.googleClientId?<div className="setup-note"><strong>{tr("Google Drive has not been configured for this deployment.","Šiame diegime Google Drive dar nesukonfigūruotas.")}</strong><p>{tr("The project owner must add the public OAuth client ID once. End users never need keys.","Projekto savininkas vieną kartą turi įvesti viešą OAuth Client ID. Naudotojams raktų nereikia.")}</p></div>:<><p>{tr("Access is limited to files created by Kairo Ride. The app does not request permission to read your entire Drive.","Prieiga ribojama Kairo Ride sukurtais failais. Programa neprašo leidimo skaityti viso Drive.")}</p><div className="button-row"><Button disabled={!p.googleReady||p.connecting||!p.online||!!p.syncMessage} onClick={p.onConnect}>{p.connecting?<LoaderCircle className="spin"/>:<Cloud/>}{p.profile?tr("Refresh access","Atnaujinti prieigą"):tr("Connect Google Drive","Prijungti Google Drive")}</Button>{p.connection&&<Button variant="outline" disabled={!!p.syncMessage||!p.online} onClick={p.onSync}><CheckCheck/>{tr("Sync now","Sinchronizuoti")}</Button>}</div></>}
          <label className="auto-sync-setting"><input type="checkbox" checked={draft.auto} onChange={event=>setDraft({...draft,auto:event.target.checked})}/><span><strong>{tr("Automatic sync","Automatinis sinchronizavimas")}</strong><small>{tr("Records sync first. Original files resume while the app is active, visible and online.","Pirmiausia sinchronizuojami įrašai. Originalūs failai tęsiami, kai programa aktyvi, matoma ir prisijungusi.")}</small></span></label>
          <p className="field-hint">{tr("Automatic sync pauses when the app is hidden or closed. Google tokens stay in memory; no client secret or personal-data server is used. Conflicts are never silently overwritten.","Automatinis sinchronizavimas sustoja paslėpus ar uždarius programą. Google žetonai laikomi atmintyje; slaptas kliento raktas ar asmens duomenų serveris nenaudojamas. Konfliktai tyliai neperrašomi.")}</p>
          {p.syncMessage&&<p role="status" className="sync-progress"><LoaderCircle className="spin"/>{p.syncMessage}</p>}{p.syncIssue&&!p.syncMessage&&<p role="status" className="sync-issue">{p.syncIssue.message} {p.autoSyncEnabled&&p.syncIssue.retry?tr("Retrying automatically while the app is active.","Bus bandoma automatiškai, kol programa aktyvi."):tr("Check access and try Sync now.","Patikrink prieigą ir bandyk sinchronizuoti.")}</p>}
          <div className="storage-summary"><span>{tr("Local changes waiting for Drive","Vietiniai pakeitimai, laukiantys Drive")}</span><strong>{p.pending}</strong><span>{tr("Original files without a Drive copy","Originalai be Drive kopijos")}</span><strong>{p.pendingFiles}</strong><span>{tr("Last sync","Paskutinis sinchronizavimas")}</span><strong>{p.cloud.lastSync?formatDate(p.cloud.lastSync,true,undefined,locale):tr("Never","Dar nebuvo")}</strong></div>
          {p.cloud.rootId&&<Button variant="outline" asChild><a href={driveFolderUrl(p.cloud.rootId)} target="_blank" rel="noopener noreferrer"><FolderOpen/>{tr("Open Kairo Ride folder","Atverti Kairo Ride aplanką")}</a></Button>}{p.profile&&<Button variant="ghost" onClick={p.onDisconnect} disabled={p.connecting}>{tr("Disconnect account","Atsijungti nuo paskyros")}</Button>}
        </section>
        <TransferCenter namespace={p.namespace} attachments={p.attachments} blobs={p.blobs} connected={p.connection} online={p.online} live={p.liveTransfers} onChanged={p.onTransferChanged} onSync={p.onSync} wakeLock={p.wakeLock} wakeLockSupported={p.wakeLockSupported} onWakeLockChange={p.onWakeLockChange}/>
      </div>
      <div hidden={section!=="transfer"}><p className="field-hint">{tr("Import, export and recovery actions run immediately; Cancel does not undo them.","Importas, eksportas ir atkūrimas atliekami iškart; Atšaukti jų neatšaukia.")}</p>
        <section className="storage-section"><h3><ArrowUpFromLine/>{tr("Import data","Duomenų importas")}</h3><p>{tr("Import a previous PWA workbook or a Kairo Ride JSON / Excel backup. A preview and recovery point are created before anything is merged.","Importuok ankstesnės PWA failą arba Kairo Ride JSON / Excel kopiją. Prieš sujungiant parodoma peržiūra ir sukuriamas atkūrimo taškas.")}</p><Field label={tr("Time zone for legacy Excel dates","Senų Excel datų laiko juosta")}><Pick value={draft.zone} onChange={value=>setDraft({...draft,zone:value})} label={tr("Excel date time zone","Excel datų laiko juosta")} options={[{value:"Europe/Vilnius",label:"Europe/Vilnius"},{value:"UTC",label:"UTC"},...(zone!=="Europe/Vilnius"&&zone!=="UTC"?[{value:zone,label:`${tr("This device","Šis įrenginys")} · ${zone}`}]:[])]}/></Field><Button variant="outline" disabled={p.importBusy||p.connecting||draft.zone!==p.importZone} onClick={p.onImport}>{p.importBusy?<LoaderCircle className="spin"/>:<ArrowUpFromLine/>}{tr("Choose import file","Pasirinkti importo failą")}</Button></section>
        <section className="storage-section"><h3><ArrowDownToLine/>{tr("Export and backup","Eksportas ir kopija")}</h3><p>{tr("Excel is for viewing and calculations. JSON is the exact history backup. Both work without Google.","Excel skirtas peržiūrai ir skaičiavimams. JSON – tiksli istorijos kopija. Abu veikia be Google.")}</p><div className="button-row"><Button variant="outline" onClick={()=>p.onExport("xlsx")}>{tr("Export Excel","Eksportuoti Excel")}</Button><Button variant="outline" onClick={()=>p.onExport("json")}>{tr("Export JSON backup","Atsisiųsti JSON kopiją")}</Button></div><p className="field-hint">{tr("Original attachments are not embedded in these exports.","Priedų originalai į šiuos eksportus neįtraukiami.")}</p></section>
        <section className="storage-section"><h3><RotateCcw/>{tr("Recovery points","Atkūrimo taškai")}</h3><p>{tr("Automatic checkpoints contain record history. Restoring one does not delete original local files.","Automatiniai taškai saugo įrašų istoriją. Jų atkūrimas neištrina vietinių originalių failų.")}</p>{p.recoverySnapshots.length?<div className="snapshot-list">{p.recoverySnapshots.map(snapshot=><div key={snapshot.key}><span><strong>{snapshot.reason}</strong><small>{formatDate(snapshot.createdAt,true,undefined,locale)} · {snapshot.operations.length} {tr("changes","pakeitimų")}</small></span><Button variant="outline" size="sm" disabled={p.importBusy} onClick={()=>{if(confirm(tr("Restore this checkpoint? A new checkpoint of the current state will be created first.","Atkurti šį tašką? Pirmiausia bus sukurtas naujas dabartinės būsenos taškas.")))void p.onRestoreSnapshot(snapshot);}}><RotateCcw/>{tr("Restore","Atkurti")}</Button></div>)}</div>:<p className="field-hint">{tr("No recovery points yet.","Atkūrimo taškų dar nėra.")}</p>}</section>
      </div>
      <div hidden={section!=="diagnostics"}><DiagnosticsPanel active={p.open&&section==="diagnostics"} namespace={p.namespace} connected={p.connection} account={p.profile?.email} pendingRecords={p.pending} pendingFiles={p.pendingFiles} conflicts={p.conflicts} lastSync={p.cloud.lastSync}/></div>
      <div hidden={section!=="info"}>
        <section className="storage-section"><h3><HardDrive/>{tr("This device","Šis įrenginys")}</h3><p>{p.offlineReady?tr("The app is ready for offline use.","Programa paruošta darbui be interneto."):tr("Offline use will be ready after the app copy is cached.","Darbas be interneto bus paruoštas išsaugojus programos kopiją.")} {tr("Clearing browser data removes local records and files that have not uploaded.","Išvalius naršyklės duomenis pašalinami vietiniai įrašai ir neįkelti failai.")}</p><p><strong>{tr("Active workspace","Aktyvi duomenų erdvė")}:</strong> {p.profile?.email??tr("Local data on this device","Vietiniai šio įrenginio duomenys")}</p><Button variant="outline" disabled={p.persisted} onClick={p.onPersist}>{p.persisted?<Check/>:<ShieldCheck/>}{p.persisted?tr("Persistent storage enabled","Patvaresnė saugykla įjungta"):tr("Request persistent storage","Paprašyti patvaresnės saugyklos")}</Button><p className="field-hint">{tr("This does not replace Drive or a backup. Data spaces for different Google accounts never merge unless you explicitly import or copy local data.","Tai nepakeičia Drive ar kopijos. Skirtingų Google paskyrų erdvės nesujungiamos, nebent aiškiai importuoji ar kopijuoji vietinius duomenis.")}</p></section>
        <section className="storage-section app-update-section"><h3><RefreshCw/>{tr("Application update","Programos atnaujinimas")}</h3><p>Kairo Ride <strong>{APP_VERSION}</strong>. {p.update?tr(`Version ${p.update.version} is fully downloaded and ready.`,`Versija ${p.update.version} visiškai atsisiųsta ir paruošta.`):tr("The app checks for a complete update while online. Installation never clears local records.","Prisijungus programa tikrina, ar yra pilnas atnaujinimas. Diegimas neišvalo vietinių įrašų.")}</p>{p.update?<Button disabled={p.updateActivating} onClick={p.onApplyUpdate}>{p.updateActivating?<LoaderCircle className="spin"/>:<RefreshCw/>}{tr("Update and restart","Atnaujinti ir paleisti iš naujo")}</Button>:<Button variant="outline" disabled={p.updateChecking} onClick={p.onCheckUpdate}>{p.updateChecking?<LoaderCircle className="spin"/>:<RefreshCw/>}{tr("Check for updates","Tikrinti atnaujinimus")}</Button>}{p.updateError&&<p role="alert" className="inline-warning">{p.updateError}</p>}<p className="field-hint">{tr("A recovery point is created before activation. An active upload must finish or be paused first.","Prieš aktyvavimą sukuriamas atkūrimo taškas. Aktyvus įkėlimas turi baigtis arba būti pristabdytas.")}</p></section>
        <section className="storage-section"><h3><Smartphone/>{tr("Install on your phone","Programėlė telefone")}</h3>{installed?<p>{tr("Kairo Ride is installed on this device.","Kairo Ride įdiegta šiame įrenginyje.")}</p>:<><p>{tr("Add the Kairo Ride icon to your home screen and open it like a standalone app.","Pridėk Kairo Ride piktogramą į pagrindinį ekraną ir atverk kaip atskirą programą.")}</p>{installPrompt&&<Button variant="outline" disabled={installing} onClick={()=>void install()}><Smartphone/>{tr("Install Kairo Ride","Įdiegti Kairo Ride")}</Button>}<p><strong>Android / Chrome:</strong> {tr("menu ⋮ → Add to home screen or Install app.","meniu ⋮ → Pridėti į pagrindinį ekraną arba Įdiegti.")}<br/><strong>iPhone / Safari:</strong> {tr("Share → Add to Home Screen → Add.","Bendrinti → Įtraukti į pagrindinį ekraną → Pridėti.")}</p></>}<p className="field-hint"><a href={appPath("privacy.html")} target="_blank" rel="noopener noreferrer">{tr("Privacy","Privatumas")}</a></p></section>
        <section className="storage-section feedback-section"><h3><Mail/>{tr("Feedback & suggestions","Pastabos ir pasiūlymai")}</h3><p>{tr("We welcome your feedback, comments and suggestions at ","Pastabų, komentarų ir pasiūlymų lauksime el. paštu ")}<a href="mailto:kairosbytomas@gmail.com">kairosbytomas@gmail.com</a>.</p></section>
      </div>
    </div>
    <div className="settings-footer"><Button variant="outline" onClick={cancel}>{tr("Cancel","Atšaukti")}</Button><Button onClick={apply}>{tr("Apply","Pritaikyti")}</Button></div>
  </DialogContent></Dialog>;
}
