"use client";
import {useEffect,useState} from "react";
import {ArrowDownToLine,ArrowUpFromLine,Bell,Check,CheckCheck,Cloud,FolderOpen,HardDrive,Languages,LoaderCircle,ShieldCheck,Smartphone} from "lucide-react";
import {toast} from "sonner";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Field,Pick} from "./forms";
import {formatDate} from "@/lib/kairo/domain";
import {driveFolderUrl,type DriveConfig} from "@/lib/kairo/drive";
import type {Profile} from "@/lib/kairo/storage";
import {appPath} from "@/lib/kairo/paths";
import {useI18n} from "@/lib/kairo/i18n";

type InstallPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
type Props={open:boolean;setOpen:(v:boolean)=>void;config:DriveConfig|null;profile:Profile|null;connection:boolean;connecting:boolean;googleReady:boolean;online:boolean;autoSyncEnabled:boolean;onAutoSyncChange:(enabled:boolean)=>void;syncIssue:{message:string;retry:boolean}|null;syncMessage:string;cloud:{rootId?:string;lastSync?:string};pending:number;pendingFiles:number;importZone:string;setImportZone:(v:string)=>void;importBusy:boolean;offlineReady:boolean;persisted:boolean;notificationsEnabled:boolean;onEnableNotifications:()=>void;onDisableNotifications:()=>void;onConnect:()=>void;onSync:()=>void;onDisconnect:()=>void;onImport:()=>void;onExport:(format:"json"|"xlsx")=>void;onPersist:()=>void};

export function StoragePanel(p:Props){
  const {tr,locale,language,setLanguage}=useI18n();
  const [installPrompt,setInstallPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(false),[installing,setInstalling]=useState(false);
  useEffect(()=>{
    const media=window.matchMedia("(display-mode: standalone)"),update=()=>setInstalled(media.matches||(navigator as Navigator&{standalone?:boolean}).standalone===true);
    const available=(event:Event)=>{event.preventDefault();setInstallPrompt(event as InstallPrompt);},done=()=>{setInstallPrompt(null);setInstalled(true);};
    update();media.addEventListener("change",update);window.addEventListener("beforeinstallprompt",available);window.addEventListener("appinstalled",done);
    return()=>{media.removeEventListener("change",update);window.removeEventListener("beforeinstallprompt",available);window.removeEventListener("appinstalled",done);};
  },[]);
  async function install(){if(!installPrompt||installing)return;setInstalling(true);try{await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);}catch{toast.info(tr("Use the browser menu and the steps below to install the app.","Naudok naršyklės meniu ir žemiau pateiktus žingsnius."));}finally{setInstalling(false);}}
  const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  return <Dialog open={p.open} onOpenChange={p.setOpen}><DialogContent className="storage-dialog"><DialogHeader><DialogTitle>{tr("Settings","Nustatymai")}</DialogTitle><DialogDescription>{tr("Language, reminders, Google Drive, backups and installation in one place.","Kalba, priminimai, Google Drive, kopijos ir diegimas vienoje vietoje.")}</DialogDescription></DialogHeader>
    <section className="storage-section settings-section"><h3><Languages/>{tr("Language","Kalba")}</h3><p>{tr("The preference is stored on this device. English remains the default for new installations.","Pasirinkimas saugomas šiame įrenginyje. Naujuose diegimuose numatytoji kalba lieka anglų.")}</p><div className="language-options"><button className={language==="en"?"active":""} onClick={()=>setLanguage("en")}><span>English</span><small>Default</small>{language==="en"&&<Check/>}</button><button className={language==="lt"?"active":""} onClick={()=>setLanguage("lt")}><span>Lietuvių</span><small>Pasirinktinai</small>{language==="lt"&&<Check/>}</button></div></section>
    <section className="storage-section settings-section"><h3><Bell/>{tr("Maintenance reminders","Priežiūros priminimai")}</h3><p>{tr("Kairo Ride checks maintenance and insurance when the PWA is open or active. A fully closed mobile PWA cannot guarantee scheduled notifications without a server.","Kairo Ride tikrina priežiūrą ir draudimą, kai PWA atidaryta arba aktyvi. Visiškai uždaryta mobilioji PWA be serverio negali garantuoti suplanuotų pranešimų.")}</p>{p.notificationsEnabled?<Button variant="outline" onClick={p.onDisableNotifications}>{tr("Disable local reminders","Išjungti vietinius priminimus")}</Button>:<Button onClick={p.onEnableNotifications}><Bell/>{tr("Enable local reminders","Įjungti vietinius priminimus")}</Button>}</section>
    <section className="drive-box"><div className="drive-heading"><span className="drive-icon"><Cloud/></span><div><h3>Google Drive</h3><p>{p.profile?.email??tr("Your private Kairo Ride folder","Tavo asmeninis Kairo Ride aplankas")}</p></div>{p.connection&&<span className="connected-dot"/>}</div>
      {p.config&&!p.config.googleClientId?<div className="setup-note"><strong>{tr("Google Drive has not been configured for this deployment.","Šiame diegime Google Drive dar nesukonfigūruotas.")}</strong><p>{tr("The project owner must add the Google OAuth client ID once. End users never need keys or configuration.","Projekto savininkas vieną kartą turi įvesti Google OAuth Client ID. Galutiniams naudotojams raktų nereikia.")}</p></div>:<><p>{tr("Access is limited to files created by Kairo Ride. The app does not request permission to read your entire Drive.","Prieiga ribojama Kairo Ride sukurtais failais. Programa neprašo leidimo skaityti viso Drive.")}</p><div className="button-row"><Button disabled={!p.googleReady||p.connecting||!p.online||!!p.syncMessage} onClick={p.onConnect}>{p.connecting?<LoaderCircle className="spin"/>:<Cloud/>}{p.profile?tr("Refresh access","Atnaujinti prieigą"):tr("Connect Google Drive","Prijungti Google Drive")}</Button>{p.connection&&<Button variant="outline" disabled={!!p.syncMessage||!p.online} onClick={p.onSync}><CheckCheck/>{tr("Sync now","Sinchronizuoti")}</Button>}</div></>}
      <label className="auto-sync-setting"><input type="checkbox" checked={p.autoSyncEnabled} onChange={event=>p.onAutoSyncChange(event.target.checked)}/><span><strong>{tr("Automatic sync","Automatinis sinchronizavimas")}</strong><small>{tr("On this device: send saved changes, check Drive every minute, and check again when you return or reconnect to the internet. Both devices need an active app and valid Google access.","Šiame įrenginyje: siųsti išsaugotus pakeitimus, tikrinti Drive kas minutę, grįžus į programą ir atsiradus internetui. Abiejuose įrenginiuose reikia aktyvios programos ir galiojančios Google prieigos.")}</small></span></label>
      <p className="field-hint">{tr("Automatic sync pauses when the app is hidden or closed. After a reload or when Google access expires, press Refresh access once. Google tokens stay in memory; no client secret or server is used. Conflicting edits remain available for review, never silently overwritten.","Automatinis sinchronizavimas sustoja paslėpus ar uždarius programą. Perkrovus programą arba pasibaigus Google prieigai paspausk Atnaujinti prieigą. Google žetonai laikomi tik atmintyje; slaptas kliento raktas ar serveris nenaudojamas. Konfliktuojantys pakeitimai lieka peržiūrai, nėra tyliai perrašomi.")}</p>
      {p.syncMessage&&<p role="status" className="sync-progress"><LoaderCircle className="spin"/>{p.syncMessage}</p>}
      {p.syncIssue&&!p.syncMessage&&<p role="status" className="sync-issue">{p.syncIssue.message} {p.autoSyncEnabled&&p.syncIssue.retry?tr("Retrying automatically while the app is active.","Bus bandoma automatiškai, kol programa aktyvi."):tr("Check access and try Sync now.","Patikrink prieigą ir bandyk sinchronizuoti.")}</p>}
      <div className="storage-summary"><span>{tr("Local changes waiting for Drive","Vietiniai pakeitimai, laukiantys Drive")}</span><strong>{p.pending}</strong><span>{tr("Original files without a Drive copy","Originalai be Drive kopijos")}</span><strong>{p.pendingFiles}</strong><span>{tr("Last sync","Paskutinis sinchronizavimas")}</span><strong>{p.cloud.lastSync?formatDate(p.cloud.lastSync,true,undefined,locale):tr("Never","Dar nebuvo")}</strong></div>
      {p.cloud.rootId&&<Button variant="outline" asChild><a href={driveFolderUrl(p.cloud.rootId)} target="_blank" rel="noopener noreferrer"><FolderOpen/>{tr("Open Kairo Ride folder","Atverti Kairo Ride aplanką")}</a></Button>}{p.profile&&<Button variant="ghost" onClick={p.onDisconnect} disabled={p.connecting}>{tr("Disconnect account","Atsijungti nuo paskyros")}</Button>}
    </section>
    <section className="storage-section"><h3><ArrowUpFromLine/>{tr("Import data","Duomenų importas")}</h3><p>{tr("Import your previous PWA file with Rides and Models sheets, or a Kairo Ride JSON / Excel backup. A preview appears before anything is written.","Importuok ankstesnės PWA failą su Rides ir Models lapais arba Kairo Ride JSON / Excel kopiją. Prieš įrašymą bus parodyta peržiūra.")}</p><Field label={tr("Time zone for legacy Excel dates","Senų Excel datų laiko juosta")} hint={tr("Used only for old PWA Excel dates that have no time zone.","Taikoma tik senos PWA Excel datoms be laiko juostos.")}><Pick value={p.importZone} onChange={p.setImportZone} label={tr("Excel date time zone","Excel datų laiko juosta")} options={[{value:"Europe/Vilnius",label:"Europe/Vilnius"},{value:"UTC",label:"UTC"},...(zone!=="Europe/Vilnius"&&zone!=="UTC"?[{value:zone,label:`${tr("This device","Šis įrenginys")} · ${zone}`}]:[])]}/></Field><Button variant="outline" disabled={p.importBusy||p.connecting} onClick={p.onImport}>{p.importBusy?<LoaderCircle className="spin"/>:<ArrowUpFromLine/>}{tr("Choose import file","Pasirinkti importo failą")}</Button></section>
    <section className="storage-section"><h3><ArrowDownToLine/>{tr("Export and backup","Eksportas ir kopija")}</h3><p>{tr("Excel is for viewing and calculations. JSON is the exact history backup. Both exports work without Google.","Excel skirtas peržiūrai ir skaičiavimams. JSON – tiksliai istorijos kopijai. Abu veikia be Google.")}</p><div className="button-row"><Button variant="outline" onClick={()=>p.onExport("xlsx")}>{tr("Export Excel","Eksportuoti Excel")}</Button><Button variant="outline" onClick={()=>p.onExport("json")}>{tr("Download JSON backup","Atsisiųsti JSON kopiją")}</Button></div><p className="field-hint">{tr("Original attachments are not embedded in these exports.","Priedų originalai į šiuos eksportus neįtraukiami.")}</p></section>
    <section className="storage-section"><h3><HardDrive/>{tr("This device","Šis įrenginys")}</h3><p>{p.offlineReady?tr("The app is ready for offline use.","Programa paruošta darbui be interneto."):tr("Offline use will be ready after the app copy is cached.","Darbas be interneto bus paruoštas išsaugojus programos kopiją.")} {tr("Clearing browser data removes local records and files that have not uploaded.","Išvalius naršyklės duomenis pašalinami vietiniai įrašai ir neįkelti failai.")}</p><Button variant="outline" disabled={p.persisted} onClick={p.onPersist}>{p.persisted?<Check/>:<ShieldCheck/>}{p.persisted?tr("Persistent storage enabled","Patvaresnė saugykla įjungta"):tr("Request persistent storage","Paprašyti patvaresnės saugyklos")}</Button><p className="field-hint">{tr("This does not replace Drive or a backup.","Tai nepakeičia Drive ar atsarginės kopijos.")}</p></section>
    <section className="storage-section"><h3><Smartphone/>{tr("Install on your phone","Programėlė telefone")}</h3>{installed?<p>{tr("Kairo Ride is installed on this device.","Kairo Ride įdiegta šiame įrenginyje.")}</p>:<><p>{tr("Add the Kairo Ride icon to your home screen and open it like a standalone app.","Pridėk Kairo Ride piktogramą į pagrindinį ekraną ir atverk kaip atskirą programą.")}</p>{installPrompt&&<Button variant="outline" disabled={installing} onClick={()=>void install()}><Smartphone/>{tr("Install Kairo Ride","Įdiegti Kairo Ride")}</Button>}<p><strong>Android / Chrome:</strong> {tr("menu ⋮ → Add to home screen or Install app.","meniu ⋮ → Pridėti į pagrindinį ekraną arba Įdiegti.")}<br/><strong>iPhone / Safari:</strong> {tr("Share → Add to Home Screen → enable Open as Web App if shown → Add.","Bendrinti → Įtraukti į pagrindinį ekraną → įjungti Open as Web App, jei rodoma → Pridėti.")}</p></>}<p className="field-hint">{tr("Open once with internet. Keep the app open while uploading large files.","Pirmą kartą atverk su internetu. Įkeliant didelius failus laikyk programą atidarytą.")} <a href={appPath("privacy.html")} target="_blank" rel="noopener noreferrer">{tr("Privacy","Privatumas")}</a></p></section>
  </DialogContent></Dialog>;
}
