"use client";
import {Cloud,HardDrive,LoaderCircle,Pause,Play,RotateCcw,Trash2,WifiOff} from "lucide-react";
import {Button} from "@/components/ui/button";
import {formatNumber} from "@/lib/kairo/numbers";
import {pauseTransfer,removeTransferFromQueue,retryTransfer,type StoredBlob,type TransferState} from "@/lib/kairo/storage";
import type {Attachment} from "@/lib/kairo/domain";
import {useI18n} from "@/lib/kairo/i18n";

export type LiveTransfer={state:TransferState;confirmedBytes:number;totalBytes:number;message:string};
const size=(bytes:number)=>bytes<1024*1024?`${formatNumber(bytes/1024,{maximumFractionDigits:0})} KB`:`${formatNumber(bytes/1024/1024,{maximumFractionDigits:1})} MB`;
export function transferView(attachment:Attachment,blob:StoredBlob,connected:boolean,online:boolean,live?:LiveTransfer){
  const state=attachment.driveId?"uploaded":live?.state??(blob.queued===false?(blob.transferState??"paused"):!online?"paused":!connected?"waiting_access":blob.transferState??"queued");
  const confirmed=Math.min(attachment.size,live?.confirmedBytes??blob.confirmedBytes??0),percent=attachment.size?Math.round(confirmed/attachment.size*100):state==="uploaded"?100:0;
  return {state,confirmed,percent,message:live?.message??blob.lastError??blob.pauseReason};
}
const stateText:Record<TransferState,[string,string]>={saved_local:["Saved locally","Išsaugota vietoje"],queued:["Queued","Eilėje"],waiting_access:["Waiting for Drive access","Laukia Drive prieigos"],uploading:["Uploading","Įkeliama"],paused:["Paused","Pristabdyta"],retrying:["Retrying","Bandoma dar kartą"],uploaded:["Uploaded","Įkelta"],failed:["Action required","Reikia veiksmo"]};
export function TransferCenter({namespace,attachments,blobs,connected,online,live,onChanged,onSync,wakeLock,wakeLockSupported,onWakeLockChange}:{namespace:string;attachments:Attachment[];blobs:StoredBlob[];connected:boolean;online:boolean;live:Record<string,LiveTransfer>;onChanged:()=>Promise<void>;onSync:()=>void;wakeLock:boolean;wakeLockSupported:boolean;onWakeLockChange:(value:boolean)=>void}){
  const {tr}=useI18n(),items=blobs.map(blob=>({blob,attachment:attachments.find(item=>item.id===blob.attachmentId)})).filter((item):item is {blob:StoredBlob;attachment:Attachment}=>!!item.attachment&&!item.attachment.archived).sort((a,b)=>(b.blob.updatedAt??b.attachment.addedAt).localeCompare(a.blob.updatedAt??a.attachment.addedAt));
  const active=items.filter(({blob,attachment})=>!["uploaded","saved_local"].includes(transferView(attachment,blob,connected,online,live[attachment.id]).state)).length;
  const change=async(run:()=>Promise<void>)=>{await run();await onChanged();};
  const resumeAll=async()=>{for(const {blob,attachment} of items)if(!attachment.driveId&&blob.queued===false&&blob.transferState!=="saved_local")await retryTransfer(namespace,attachment.id);await onChanged();onSync();};
  return <section className="storage-section transfer-center"><div className="transfer-heading"><div><h3><Cloud/>{tr("Transfers","Failų perdavimai")}</h3><p>{active?`${active} ${tr("files still need attention or upload.","failams dar reikia veiksmo arba įkėlimo.")}`:tr("No pending uploads. It is safe to close the app.","Laukiančių įkėlimų nėra. Programą galima saugiai uždaryti.")}</p></div>{active>0&&<Button variant="outline" disabled={!connected||!online} onClick={()=>void resumeAll()}><RotateCcw/>{tr("Resume all","Tęsti visus")}</Button>}</div>
    <p className="field-hint">{tr("Files are saved on this device before upload. Android may pause a PWA when it is hidden or the screen is off; reopen Kairo Ride to resume from Google's confirmed byte position.","Prieš įkėlimą failai išsaugomi šiame įrenginyje. Android gali pristabdyti paslėptą PWA ar išjungus ekraną; atverk Kairo Ride ir įkėlimas tęsis nuo Google patvirtintos vietos.")}</p>
    {wakeLockSupported&&<label className="auto-sync-setting compact"><input type="checkbox" checked={wakeLock} onChange={event=>onWakeLockChange(event.target.checked)}/><span><strong>{tr("Keep screen awake while uploading","Įkeliant neleisti ekranui užmigti")}</strong><small>{tr("Used only while a file is actively uploading and the app is visible.","Veikia tik aktyviai įkeliant failą ir matant programą.")}</small></span></label>}
    {!items.length?<div className="transfer-empty"><HardDrive/><span>{tr("Trip files saved on this device will appear here.","Šiame įrenginyje išsaugoti kelionių failai bus rodomi čia.")}</span></div>:<div className="transfer-list">{items.map(({attachment,blob})=>{const item=transferView(attachment,blob,connected,online,live[attachment.id]),working=item.state==="uploading"||item.state==="retrying";return <article className={`transfer-item transfer-${item.state}`} key={attachment.id}><div className="transfer-title"><span>{working?<LoaderCircle className="spin"/>:item.state==="uploaded"?<Cloud/>:!online?<WifiOff/>:<HardDrive/>}</span><div><strong>{attachment.name}</strong><small>{size(attachment.size)} · {tr(...stateText[item.state])}</small></div><b>{item.percent}%</b></div><div className="transfer-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={item.percent}><i style={{width:`${item.percent}%`}}/></div>{item.message&&<p className="transfer-message">{item.message}</p>}<div className="button-row">{blob.queued!==false&&!attachment.driveId&&<Button size="sm" variant="outline" onClick={()=>void change(()=>pauseTransfer(namespace,attachment.id))}><Pause/>{tr("Pause","Pristabdyti")}</Button>}{blob.queued===false&&!attachment.driveId&&<Button size="sm" variant="outline" onClick={()=>void change(()=>retryTransfer(namespace,attachment.id)).then(onSync)}><Play/>{tr("Queue / resume","Į eilę / tęsti")}</Button>}{!attachment.driveId&&<Button size="sm" variant="ghost" onClick={()=>void change(()=>removeTransferFromQueue(namespace,attachment.id))}><Trash2/>{tr("Remove from queue","Išimti iš eilės")}</Button>}</div></article>;})}</div>}
  </section>;
}
