"use client";
import {formatNumber} from "@/lib/kairo/numbers";
import {useEffect,useRef,useState,type ReactNode} from "react";
import {
  ArrowDown,ArrowUp,ArrowDownToLine,ArrowRight,ArrowUpFromLine,Backpack,Battery,
  CalendarClock,Camera,Cable,ChevronDown,ChevronLeft,ChevronRight,File,Footprints,Gauge,Hand,Headphones,
  Mountain,Package,Paperclip,Pencil,Plus,Route,Search,Shield,Shirt,Trash2,TriangleAlert,Wrench,
} from "lucide-react";
import {
  Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,
} from "recharts";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from "@/components/ui/empty";
import {TabsContent} from "@/components/ui/tabs";
import {Pick,type EditableKind} from "./forms";
import {VehicleCard,TripTable,MaintenanceCalendar} from "./overview-extras";
import {RideTable} from "./ride-table";
import {VehicleStatusBadge} from "./vehicle-status";
import {AnalyticsView} from "./history-charts";
import {orderedVehicles,vehicleSelectOptions} from "@/lib/kairo/vehicle-status";
import {
  GEAR_CATEGORIES,GEAR_STATUSES,gearCategoryLabels,gearStatusLabels,maintenanceCategoryLabels,
  canRecordWithWheel,formatDate,formatKm,wheelStats,
  type Attachment,type Goal,type Entity,type Gear,type Kind,type Maintenance,type Reading,type Ride,type State,type Trip,type Wheel,
} from "@/lib/kairo/domain";
import {driveFileUrl} from "@/lib/kairo/drive";
import {maintenanceOdometer,templateForMaintenance} from "@/lib/kairo/maintenance";
import {useI18n,ltGearCategories,ltGearStatuses,ltMaintenanceCategories} from "@/lib/kairo/i18n";
import {
  averageDistance,dueMaintenance,fitChartDomain,maintenanceStatus,metricDistance,periodData,rideEntries,tripRideStats,
  type AverageUnit,type ChartMode,type MaintenanceStatus,
} from "@/lib/kairo/stats";

export type Detail={kind:"trip"|"ride"|"reading";id:string;edit?:boolean};
export type View="overview"|"rides"|"trips"|"wheels"|"gear"|"analytics";
export type ViewActions={openEditor:(kind:EditableKind,entity?:Entity,tripId?:string)=>void;openRide:(ride?:Ride,reading?:Reading,tripId?:string)=>void;askDelete:(kind:Kind,entity:Entity,linkedReading?:Reading)=>void;setDetail:(d:Detail)=>void;addGoal:(targetKm:number,wheelId:string|null)=>Promise<void>;saveGoal?:(goal:Goal,parents:string[])=>Promise<void>;selectedGoal?:string;selectGoal?:(id:string)=>void};

const chartStyle={background:"#111217",border:"1px solid #2c2e34",borderRadius:10,color:"#f5f3ef"};

function InteractiveLegend({wheels,hidden,onToggle,state}:{wheels:Wheel[];hidden:Set<string>;onToggle:(id:string)=>void;state:State}){
  const {tr}=useI18n();
  return <div className="interactive-legend" aria-label={tr("Chart vehicles","Grafiko priemonės")}>{wheels.map(wheel=>{const active=!hidden.has(wheel.id);return <button type="button" key={wheel.id} className={active?"active":""} aria-pressed={active} onClick={()=>onToggle(wheel.id)}><i style={{background:wheel.color}}/><span>{wheel.name}</span>{!canRecordWithWheel(wheel)&&<VehicleStatusBadge wheel={wheel} state={state}/>}</button>;})}</div>;
}

export function Blank({icon:Icon,title,description,children}:{icon:typeof Route;title:string;description:string;children?:ReactNode}){
  return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><Icon/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>;
}

export function SmallActions({edit}:{edit:()=>void;remove:()=>void}){
  const {tr}=useI18n();
  return <div className="row-actions"><Button variant="ghost" size="icon" onClick={edit} aria-label={tr("Edit","Redaguoti")}><Pencil/></Button></div>;
}

export function RideRow({ride,state,actions}:{ride:Ride;state:State;actions:ViewActions}){
  const {tr,locale}=useI18n(),wheel=state.wheel.find(w=>w.id===ride.wheelId),trip=state.trip.find(t=>t.id===ride.tripId),count=state.attachment.filter(a=>a.ownerKind==="ride"&&a.ownerId===ride.id).length,entry=rideEntries(state).find(item=>item.ride?.id===ride.id),reading=entry?.reading;
  return <article className="ride-row"><button className="ride-primary" onClick={()=>actions.setDetail({kind:"ride",id:ride.id})}><span className="ride-dot" style={{background:wheel?.color}}><Route/></span><span className="ride-text"><strong>{ride.name||tr("Ride","Važiavimas")}</strong><span>{formatDate(ride.at,true,ride.timeZone,locale)} · {wheel?.name??tr("Vehicle unavailable","Transporto priemonė nepasiekiama")}</span>{trip&&<span className="trip-label"><Mountain/>{trip.name}</span>}</span><span className="ride-distance">{formatKm(entry?.distanceKm??null,locale)}<small>km</small>{count>0&&<span className="attachment-count"><Paperclip/>{count}</span>}</span><ChevronRight className="muted"/></button><SmallActions edit={()=>actions.openRide(ride,reading)} remove={()=>actions.askDelete("ride",ride,reading)}/></article>;
}

export function TripCard({trip,state,actions}:{trip:Trip;state:State;actions:ViewActions}){
  const {tr,locale}=useI18n(),stats=tripRideStats(trip,state);
  return <article className="trip-card"><button onClick={()=>actions.setDetail({kind:"trip",id:trip.id})} className="trip-card-main"><div className="trip-card-top"><span className="trip-icon"><Mountain/></span><span className="eyebrow">{stats.days} {tr("days","d.")}</span><ChevronRight/></div><h3>{trip.name}</h3><p>{formatDate(trip.startDate,false,undefined,locale)} <span>→</span> {formatDate(trip.endDate,false,undefined,locale)}</p><div className="trip-card-stats"><span><strong>{formatKm(stats.distanceKm,locale)}</strong> km{stats.unknownDistances>0?" + ?":""}</span><span>{stats.rides.length} {tr("rides","važiav.")}</span><span><Paperclip/>{stats.attachments.length}</span></div></button><div className="trip-card-footer"><span>{trip.notes?trip.notes.slice(0,85):tr("Trip notes and files","Kelionės užrašai ir failai")}</span><SmallActions edit={()=>actions.openEditor("trip",trip)} remove={()=>actions.askDelete("trip",trip)}/></div></article>;
}

const bytes=(n:number)=>n<1024?`${n} B`:n<1024*1024?`${formatNumber(n/1024,{maximumFractionDigits:0})} KB`:`${formatNumber(n/1024/1024,{maximumFractionDigits:1})} MB`;
const gearIcons={helmet:Shield,footwear:Footprints,protection:Shield,gloves:Hand,clothing:Shirt,camera:Camera,intercom:Headphones,bag:Backpack,charging:Cable,other:Package};

function GearCard({gear,state,actions}:{gear:Gear;state:State;actions:ViewActions}){
  const {tr,language,locale}=useI18n(),Icon=gearIcons[gear.category];
  const category=language==="lt"?ltGearCategories[gear.category]:gearCategoryLabels[gear.category];
  const status=language==="lt"?ltGearStatuses[gear.status]:gearStatusLabels[gear.status];
  const links=(gear.usedWithGearIds??[]).map(id=>state.gear.find(item=>item.id===id)?.name).filter(Boolean);
  return <details className="gear-card gear-expandable panel"><summary className="gear-summary"><span className="gear-icon" title={category}><Icon/></span><h2>{gear.name}</h2><ChevronDown className="gear-chevron"/></summary><div className="gear-body"><div className="section-heading"><p className="eyebrow">{category}</p><SmallActions edit={()=>actions.openEditor("gear",gear)} remove={()=>actions.askDelete("gear",gear)}/></div><span className={`gear-status gear-status-${gear.status}`}>{status}</span>{(gear.brand||gear.model||gear.size||gear.purchasedOn||links.length>0)&&<dl>{gear.brand&&<div><dt>{tr("Brand","Gamintojas")}</dt><dd>{gear.brand}</dd></div>}{gear.model&&<div><dt>{tr("Model","Modelis")}</dt><dd>{gear.model}</dd></div>}{gear.size&&<div><dt>{tr("Size","Dydis")}</dt><dd>{gear.size}</dd></div>}{gear.purchasedOn&&<div><dt>{tr("Purchased","Įsigyta")}</dt><dd>{formatDate(gear.purchasedOn,false,undefined,locale)}</dd></div>}{links.length>0&&<div><dt>{tr("Used with","Kur naudojama")}</dt><dd>{links.join(", ")}</dd></div>}</dl>}{gear.notes&&<details className="gear-notes"><summary>{tr("Notes","Pastabos")}</summary><p className="preserve-lines">{gear.notes}</p></details>}</div></details>;
}

export function MaintenanceCard({item,state,actions}:{item:Maintenance;state:State;actions:ViewActions}){
  const {tr,language,locale}=useI18n(),status=maintenanceStatus(item,state);
  const target=(item.targetKind==="wheel"?state.wheel:state.gear).find(entity=>entity.id===item.targetId);
  const label=language==="lt"?ltMaintenanceCategories[item.category]:maintenanceCategoryLabels[item.category];
  const statusLabels:Record<MaintenanceStatus,string>={completed:tr("Completed","Atlikta"),overdue:tr("Overdue","Vėluoja"),due:tr("Due now","Laikas atlikti"),upcoming:tr("Upcoming","Artėja"),planned:tr("Planned","Suplanuota")};
  const Icon=item.category==="insurance"?Shield:item.category==="battery"?Battery:Wrench;
  const template=item.templateId?templateForMaintenance(item):undefined,odometer=maintenanceOdometer(state,item.targetKind,item.targetId);
  const heading=template?(template.group==="condition"?tr("Condition / component-based work","Darbai pagal būklę / komponentą"):template.group==="inspection"?tr("Inspection","Patikra"):label):label;
  return <details className={`maintenance-card panel maintenance-${status}`}><summary className="vehicle-summary"><strong>{item.title}</strong><span className={`maintenance-status status-${status}`}>{statusLabels[status]}</span><ChevronDown/></summary><div className="gear-body">
    <div className="section-heading"><span className="gear-icon"><Icon/></span><SmallActions edit={()=>actions.openEditor("maintenance",item)} remove={()=>actions.askDelete("maintenance",item)}/></div>
    <p className="eyebrow">{heading}</p><h2>{item.title}</h2><span className={`maintenance-status status-${status}`}>{statusLabels[status]}</span>
    {item.dueDate&&item.dueOdometerKm!==null&&!item.completedAt&&<p className="field-hint">{tr("Whichever comes first: date or mileage.","Kas sueina pirmiau: data ar rida.")}</p>}
    {!item.dueDate&&item.dueOdometerKm===null&&!item.completedAt&&<p className="field-hint">{template?.cadence[language]??tr("Unscheduled checklist","Patikra be termino")}</p>}
    <dl>
      <div><dt>{tr("Applies to","Kam taikoma")}</dt><dd>{target?.name??tr("Unavailable","Nepasiekiama")}</dd></div>
      {item.dueDate&&<div><dt>{item.category==="insurance"?tr("Valid until","Galioja iki"):tr("Due date","Atlikimo data")}</dt><dd>{formatDate(item.dueDate,false,undefined,locale)}</dd></div>}
      {item.dueOdometerKm!==null&&<div><dt>{tr("Due odometer","Atlikimo odometras")}</dt><dd>{formatKm(item.dueOdometerKm,locale)} km</dd></div>}
      {item.dueOdometerKm!==null&&odometer!==null&&!item.completedAt&&<div><dt>{tr("Distance remaining","Liko atstumo")}</dt><dd>{odometer>=item.dueOdometerKm?tr("Target reached","Tikslas pasiektas"):`${formatKm(item.dueOdometerKm-odometer,locale)} km`}</dd></div>}
      {item.remindDaysBefore!==null&&item.dueDate&&<div><dt>{tr("Reminder","Priminimas")}</dt><dd>{item.remindDaysBefore} {tr("days before","d. prieš")}</dd></div>}
      {item.repeatKm!==null&&<div><dt>{tr("Repeat","Kartoti")}</dt><dd>{formatKm(item.repeatKm,locale)} km</dd></div>}
      {item.repeatDays!=null&&<div><dt>{tr("Repeat","Kartoti")}</dt><dd>{item.repeatDays} {tr("days","d.")}</dd></div>}
      {item.repeatMonths!==null&&<div><dt>{tr("Repeat","Kartoti")}</dt><dd>{item.repeatMonths} {tr("months","mėn.")}</dd></div>}
      {item.completedAt&&<div><dt>{tr("Completed","Atlikta")}</dt><dd>{formatDate(item.completedAt,true,undefined,locale)}</dd></div>}
    </dl>
    {template&&<details className="maintenance-guidance"><summary>{tr("What to check / suggested interval","Ką tikrinti / siūlomas intervalas")}</summary><strong>{template.cadence[language]}</strong><p>{template.guidance[language]}</p><p>{tr("Suggested reminder, not an official manufacturer schedule. Manufacturer instructions take priority.","Siūlomas priminimas, ne oficialus gamintojo grafikas. Gamintojo instrukcija turi pirmenybę.")}</p></details>}
    {item.notes&&<p className="maintenance-notes preserve-lines">{item.notes}</p>}
  </div></details>;
}

export function FileListView({files,localIds,onDownload,onDelete,editable=false}:{files:Attachment[];localIds:Set<string>;onDownload:(a:Attachment)=>void;onDelete:(a:Attachment)=>void;editable?:boolean}){
  const {tr}=useI18n();
  return <div className="file-list">{files.map(a=><div className="file-row" key={a.id}><div className="file-badge"><File/><span>{a.name.split(".").at(-1)?.slice(0,5).toUpperCase()}</span></div><div className="file-info"><strong>{a.name}</strong><span>{bytes(a.size)} · {a.driveId?"Google Drive":localIds.has(a.id)?tr("This device only","Tik šiame įrenginyje"):tr("Original not downloaded yet","Originalas dar neatsiųstas")}</span></div><div className="row-actions">{a.driveId?<Button variant="outline" size="sm" asChild><a href={driveFileUrl(a.driveId)} target="_blank" rel="noopener noreferrer">{tr("Open","Atverti")} <ArrowRight/></a></Button>:<Button variant="outline" size="icon" disabled={!localIds.has(a.id)} onClick={()=>onDownload(a)} aria-label={`${tr("Download","Atsisiųsti")} ${a.name}`}><ArrowDownToLine/></Button>}{editable&&<Button variant="ghost" size="icon" aria-label={`${tr("Remove link","Pašalinti nuorodą")} ${a.name}`} onClick={()=>onDelete(a)}><Trash2/></Button>}</div></div>)}</div>;
}

function PeriodChart({state}:{state:State}){
  const {tr,locale,weekStartsOn,dateFormat}=useI18n(),[mode,setMode]=useState<ChartMode>("week"),[offset,setOffset]=useState(0),[hidden,setHidden]=useState<Set<string>>(()=>new Set()),touchStart=useRef<number|null>(null);
  const period=periodData(state,mode,offset,locale,new Date(),weekStartsOn,dateFormat);
  const visible=state.wheel.filter(wheel=>!hidden.has(wheel.id));
  const visibleTotal=period.points.reduce((sum,point)=>sum+visible.reduce((value,wheel)=>value+Number(point[wheel.id]??0),0),0);
  const data={...period,total:visibleTotal};
  const changeMode=(next:string)=>{setMode(next as ChartMode);setOffset(0);};
  const toggle=(id:string)=>setHidden(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
  function swipe(end:number){if(touchStart.current===null)return;const distance=end-touchStart.current;touchStart.current=null;if(Math.abs(distance)<45)return;if(distance>0)setOffset(value=>value-1);else setOffset(value=>Math.min(0,value+1));}
  return <section className="dashboard-chart panel"><div className="chart-heading"><div><p className="eyebrow">{tr("DISTANCE BY DAY","ATSTUMAS PAGAL DIENĄ")}</p><h2>{data.title}</h2><span>{formatKm(data.total,locale)} km</span></div><div className="chart-controls"><div className="segmented"><button className={mode==="week"?"active":""} onClick={()=>changeMode("week")}>{tr("Week","Savaitė")}</button><button className={mode==="month"?"active":""} onClick={()=>changeMode("month")}>{tr("Month","Mėnuo")}</button></div><Button variant="ghost" size="icon" onClick={()=>setOffset(value=>value-1)} aria-label={tr("Previous period","Ankstesnis laikotarpis")}><ChevronLeft/></Button><Button variant="ghost" size="icon" disabled={offset===0} onClick={()=>setOffset(value=>Math.min(0,value+1))} aria-label={tr("Next period","Kitas laikotarpis")}><ChevronRight/></Button></div></div><InteractiveLegend wheels={orderedVehicles(state.wheel)} hidden={hidden} onToggle={toggle} state={state}/><div className="chart-touch" onTouchStart={event=>{touchStart.current=event.changedTouches[0].clientX;}} onTouchEnd={event=>swipe(event.changedTouches[0].clientX)}><ResponsiveContainer width="100%" height={300}><BarChart key={visible.map(wheel=>wheel.id).join("|")} data={data.points} accessibilityLayer margin={{top:12,right:10,left:-14,bottom:0}}><CartesianGrid stroke="#292b31" vertical={false}/><XAxis dataKey="label" tick={{fill:"#8e9098",fontSize:11}} axisLine={false} tickLine={false} interval={mode==="month"?2:0}/><YAxis tickFormatter={value=>formatNumber(Number(value))} domain={fitChartDomain(data.points,visible.map(wheel=>wheel.id),"grouped")} allowDataOverflow tick={{fill:"#8e9098",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={value=>formatNumber(Number(value))} contentStyle={chartStyle} cursor={{fill:"rgba(255,255,255,.035)"}} labelFormatter={(_label,payload)=>{const date=payload?.[0]?.payload?.date;return date?formatDate(date,false,undefined,locale):"";}}/>{visible.map(wheel=><Bar key={wheel.id} dataKey={wheel.id} name={wheel.name} fill={wheel.color} radius={[3,3,0,0]} activeBar={{fillOpacity:.9,stroke:"rgba(255,255,255,.14)"}} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></div><p className="chart-hint">{tr("Swipe right for an older period and left to return towards the present. Tap a vehicle in the legend to hide or show it.","Brauk dešinėn ankstesniam laikotarpiui, kairėn – grįžti dabarties link. Paspausk priemonę legendoje, kad ją paslėptum arba parodytum.")}</p></section>;
}

export function DashboardHero({state}:{state:State}){
  const {tr,locale,language,weekStartsOn}=useI18n();
  const [unit,setUnitState]=useState<AverageUnit|"ride"|"trip">(()=>{const value=typeof localStorage!=="undefined"?localStorage.getItem("kairo-dashboard-metric"):null;return ["day","week","month","ride","trip"].includes(value??"")?value as AverageUnit|"ride"|"trip":"ride";});
  const [wheelId,setWheelIdState]=useState(()=>typeof localStorage!=="undefined"?localStorage.getItem("kairo-dashboard-wheel")??"all":"all");
  const setUnit=(value:string)=>{localStorage.setItem("kairo-dashboard-metric",value);setUnitState(value as AverageUnit|"ride"|"trip");};
  const setWheelId=(value:string)=>{localStorage.setItem("kairo-dashboard-wheel",value);setWheelIdState(value);};
  const labels:Record<AverageUnit,string>={day:tr("Average kilometres per day","Vidutiniškai kilometrų per dieną"),week:tr("Average kilometres per week","Vidutiniškai kilometrų per savaitę"),month:tr("Average kilometres per month","Vidutiniškai kilometrų per mėnesį")};
  const units:Record<AverageUnit,string>={day:"km/d",week:"km/w",month:"km/m"};
  const selectedWheel=state.wheel.some(w=>w.id===wheelId)?wheelId:"all";
  const lastRide=rideEntries(state).find(r=>selectedWheel==="all"||r.wheelId===selectedWheel);
  const lastTrip=state.trip.filter(t=>!t.archived&&(selectedWheel==="all"||state.ride.some(r=>r.tripId===t.id&&r.wheelId===selectedWheel))).sort((a,b)=>b.endDate.localeCompare(a.endDate)||b.startDate.localeCompare(a.startDate))[0];
  const primary=unit==="ride"?lastRide?.distanceKm??null:unit==="trip"?lastTrip?tripRideStats(lastTrip,state).distanceKm:null:averageDistance(state,unit);
  const primaryLabel=unit==="ride"?tr("Last ride","Paskutinis įrašas"):unit==="trip"?tr("Last trip","Paskutinė kelionė"):labels[unit];
  return <section className="dashboard-hero"><div className="hero-slash"/><div className="hero-controls"><Pick label={tr("Long-term average","Ilgalaikis vidurkis")} value={unit} onChange={setUnit} options={[{value:"ride",label:tr("Last ride","Paskutinis įrašas")},{value:"trip",label:tr("Last trip","Paskutinė kelionė")},...(Object.keys(labels) as AverageUnit[]).map(value=>({value,label:`${units[value]} · ${labels[value]}`}))]}/><Pick label={tr("Secondary statistics vehicle","Smulkesnės statistikos priemonė")} value={selectedWheel} onChange={setWheelId} options={[{value:"all",label:tr("All vehicles","Visos priemonės")},...vehicleSelectOptions(state,language)]}/></div><div className="hero-primary"><p>{primaryLabel} · {unit==="ride"?lastRide?`${formatDate(lastRide.at,true,undefined,locale)} · ${state.wheel.find(w=>w.id===lastRide.wheelId)?.name??""}`:tr("No records","Įrašų nėra"):unit==="trip"?lastTrip?.name??tr("No trips","Kelionių nėra"):tr("all vehicles, all time","visos priemonės, visas laikas")}</p><strong>{formatKm(primary,locale)}</strong><span>{unit==="ride"||unit==="trip"?"km":units[unit]}</span></div><div className="hero-vehicle-scope" aria-live="polite">{selectedWheel==="all"?tr("All vehicles","Visos priemonės"):state.wheel.find(wheel=>wheel.id===selectedWheel)?.name}</div><div className="hero-secondary"><div><strong>{formatKm(metricDistance(state,"week",selectedWheel,new Date(),weekStartsOn),locale)} km</strong><span>{tr("This week","Šią savaitę")}</span></div><div><strong>{formatKm(metricDistance(state,"month",selectedWheel),locale)} km</strong><span>{tr("This month","Šį mėnesį")}</span></div><div><strong>{formatKm(metricDistance(state,"year",selectedWheel),locale)} km</strong><span>{tr("This year","Šiais metais")}</span></div><div><strong>{formatKm(metricDistance(state,"all",selectedWheel),locale)} km</strong><span>{tr("All time","Iš viso")}</span></div></div></section>;
}

function FleetStrip({state,onSelect,onGarage}:{state:State;onSelect:(id:string)=>void;onGarage:()=>void}){
  const {tr,locale}=useI18n(),fleet=orderedVehicles(state.wheel.filter(w=>!w.archived)).map(wheel=>({wheel,...wheelStats(wheel,state.reading)}));
  const strip=useRef<HTMLDivElement>(null),order=fleet.map(item=>item.wheel.id).join("|");
  useEffect(()=>{const frame=requestAnimationFrame(()=>{if(strip.current)strip.current.scrollLeft=0;});return()=>cancelAnimationFrame(frame);},[order]);
  return <section className="fleet-section"><div className="section-heading"><div><p className="eyebrow">{tr("FLEET","PARKAS")}</p><h2>{tr("Your vehicles","Tavo transporto priemonės")}</h2></div></div>{fleet.length?<div className="fleet-strip" ref={strip} key={order}>{fleet.map(item=><article role="button" tabIndex={0} onClick={()=>onSelect(item.wheel.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(item.wheel.id);}}} className={!canRecordWithWheel(item.wheel)?"fleet-inactive":""} key={item.wheel.id} style={{"--wheel-color":item.wheel.color} as React.CSSProperties}><span className="fleet-name">{item.wheel.name}</span><strong>{formatKm(item.trackedKm,locale)} km</strong><VehicleStatusBadge wheel={item.wheel} state={state}/></article>)}</div>:<div className="panel"><Blank icon={Gauge} title={tr("Your fleet starts here","Tavo parkas prasideda čia")} description={tr("Add a vehicle and its baseline odometer.","Pridėk transporto priemonę ir pradinį odometrą.")}><Button onClick={onGarage}>{tr("Open Garage","Atverti garažą")}</Button></Blank></div>}</section>;
}


export function MainViews({state,actions,setView,openStorage}:{state:State;actions:ViewActions;setView:(v:View)=>void;openStorage:()=>void}){
  const {tr,language,locale}=useI18n(),{openEditor,openRide}=actions;
  const [focusedWheel,setFocusedWheel]=useState("");
  const [gearSort,setGearSort]=useState<"name"|"category"|"status">("name"),[gearAsc,setGearAsc]=useState(true);
  const sortGear=(key:"name"|"category"|"status")=>{if(gearSort===key)setGearAsc(!gearAsc);else{setGearSort(key);setGearAsc(true);}};
  const [garageMode,setGarageMode]=useState<"fleet"|"maintenance">("fleet");
  const openGarage=()=>{setGarageMode("fleet");setView("wheels");};
  const [filterGear,setFilterGear]=useState("all"),[filterGearStatus,setFilterGearStatus]=useState("all"),[gearSearch,setGearSearch]=useState("");
  const search=gearSearch.trim().toLocaleLowerCase(locale),visibleGear=state.gear.filter(g=>!g.archived&&(filterGear==="all"||g.category===filterGear)&&(filterGearStatus==="all"||g.status===filterGearStatus)&&[g.name,g.brand,g.model,g.size,g.notes,language==="lt"?ltGearCategories[g.category]:gearCategoryLabels[g.category]].join(" ").toLocaleLowerCase(locale).includes(search)).sort((a,b)=>(gearAsc?1:-1)*(gearSort==="category"?(language==="lt"?ltGearCategories[a.category]:gearCategoryLabels[a.category]).localeCompare(language==="lt"?ltGearCategories[b.category]:gearCategoryLabels[b.category],locale):gearSort==="status"?(language==="lt"?ltGearStatuses[a.status]:gearStatusLabels[a.status]).localeCompare(language==="lt"?ltGearStatuses[b.status]:gearStatusLabels[b.status],locale):a.name.localeCompare(b.name,locale))||a.id.localeCompare(b.id));
  const totals=orderedVehicles(state.wheel.filter(w=>!w.archived)).map(w=>({wheel:w,...wheelStats(w,state.reading)})),warnings=totals.reduce((n,s)=>n+s.warnings,0),due=dueMaintenance(state);
  const gearCategory=(value:Gear["category"])=>language==="lt"?ltGearCategories[value]:gearCategoryLabels[value],gearStatus=(value:Gear["status"])=>language==="lt"?ltGearStatuses[value]:gearStatusLabels[value];
  return <>
    <TabsContent value="overview"><section className="page-heading home-heading"><div><p className="eyebrow">{tr("RIDE BEYOND LIMITS","RIEDĖK BE RIBŲ")}</p><h1>{tr("Good to have you back.","Gera vėl riedėti.")}</h1><p>{tr("Your fleet, distance and adventures — at a glance.","Tavo parkas, rida ir nuotykiai – vienu žvilgsniu.")}</p></div><Button onClick={()=>state.wheel.length?openRide():openGarage()}><Plus/>{state.wheel.length?tr("New ride","Naujas važiavimas"):tr("Open Garage","Atverti garažą")}</Button></section><DashboardHero state={state}/>{due.length>0&&<div className="notice maintenance-notice"><CalendarClock/><span><strong>{due.length}</strong> {tr("maintenance or insurance items need attention.","priežiūros ar draudimo įrašams reikia dėmesio.")}</span><Button variant="outline" size="sm" onClick={()=>{setGarageMode("maintenance");setView("wheels");}}>{tr("Review","Peržiūrėti")}</Button></div>}<FleetStrip state={state} onGarage={()=>{setGarageMode("fleet");setView("wheels");}} onSelect={id=>{setFocusedWheel(id);setGarageMode("fleet");setView("wheels");}}/><PeriodChart state={state}/>{!state.wheel.length&&!state.trip.length&&<section className="start-panel"><div><span className="eyebrow">{tr("START WITH YOUR DATA","PRADĖK NUO SAVO DUOMENŲ")}</span><h2>{tr("Your ride archive starts here.","Tavo archyvas prasideda čia.")}</h2><p>{tr("Add a vehicle and its baseline odometer, or import your previous PWA Excel file.","Pridėk priemonę ir jos pradinį odometrą arba importuok ankstesnį PWA Excel failą.")}</p></div><div className="start-actions"><Button onClick={()=>openGarage()}><Plus/>{tr("Open Garage","Atverti garažą")}</Button><Button variant="outline" onClick={openStorage}><ArrowUpFromLine/>{tr("Import data","Importuoti duomenis")}</Button></div></section>}{warnings>0&&<div className="notice warning"><TriangleAlert/><span>{warnings} {tr("ride odometer values need attention.","važiavimų odometro reikšmes reikia patikrinti.")}</span><Button variant="ghost" size="sm" onClick={()=>setView("rides")}>{tr("Review","Peržiūrėti")}</Button></div>}<section className="section"><div className="section-heading"><div><p className="eyebrow">{tr("MORE THAN DISTANCE","DAUGIAU NEI KILOMETRAI")}</p><h2>{tr("Latest trips","Naujausios kelionės")}</h2></div><Button variant="outline" onClick={()=>openEditor("trip")}><Plus/>{tr("New trip","Nauja kelionė")}</Button></div>{state.trip.length?<div className="trip-grid">{state.trip.filter(t=>!t.archived).slice(0,3).map(t=><TripCard key={t.id} trip={t} state={state} actions={actions}/>)}</div>:<div className="trip-empty"><Mountain/><div><h3>{tr("Space for your next trip.","Vieta tavo kitai kelionei.")}</h3><p>{tr("Keep rides, GPX, logs, photos and video together.","Laikyk važiavimus, GPX, logus, nuotraukas ir video kartu.")}</p></div><Button variant="ghost" onClick={()=>openEditor("trip")}>{tr("Create trip","Sukurti kelionę")} <ArrowRight/></Button></div>}</section></TabsContent>

    <TabsContent value="rides"><section className="page-heading"><div><p className="eyebrow">{tr("ONE RIDE. ONE COMPLETE RECORD.","VIENAS VAŽIAVIMAS. VIENAS PILNAS ĮRAŠAS.")}</p><h1>{tr("Rides","Važiavimai")}</h1><p>{tr("Ride records, odometer history, trip links and notes. Files belong to Trips.","Važiavimų įrašai, odometras, kelionės ir pastabos. Failai priskiriami kelionėms.")}</p></div><Button onClick={()=>state.wheel.length?openRide():openEditor("wheel")}><Plus/>{tr("New ride","Naujas važiavimas")}</Button></section>{rideEntries(state).length?<RideTable state={state} actions={actions}/>:<div className="panel"><Blank icon={Route} title={tr("Your first ride is waiting","Pirmas važiavimas laukia")} description={tr("Enter the final odometer value. Distance is calculated automatically; a ride name is optional. You can also create or select a trip.","Įvesk galutinį odometrą. Atstumas skaičiuojamas automatiškai; pavadinimas neprivalomas. Taip pat gali sukurti arba pasirinkti kelionę.")}><Button onClick={()=>state.wheel.length?openRide():openEditor("wheel")}><Plus/>{tr("Start","Pradėti")}</Button></Blank></div>}</TabsContent>

    <TabsContent value="trips"><section className="page-heading"><div><p className="eyebrow">{tr("MANY DAYS. ONE STORY.","KELIOS DIENOS. VIENA ISTORIJA.")}</p><h1>{tr("Trips","Kelionės")}</h1><p>{tr("Rides, memories and original files in one place.","Važiavimai, prisiminimai ir originalūs failai vienoje vietoje.")}</p></div><Button onClick={()=>openEditor("trip")}><Plus/>{tr("New trip","Nauja kelionė")}</Button></section>{state.trip.length?<TripTable state={state} actions={actions}/>:<div className="panel"><Blank icon={Mountain} title={tr("Where would you like to go?","Kur norėtum išvažiuoti?")} description={tr("Create a one-day, weekend or multi-week trip.","Sukurk vienos dienos, savaitgalio ar kelių savaičių kelionę.")}><Button onClick={()=>openEditor("trip")}><Plus/>{tr("Create trip","Sukurti kelionę")}</Button></Blank></div>}</TabsContent>

    <TabsContent value="wheels"><section className="page-heading"><div><p className="eyebrow">{tr("FLEET AND CARE","PARKAS IR PRIEŽIŪRA")}</p><h1>{garageMode==="fleet"?tr("Garage","Garažas"):tr("Maintenance","Priežiūra")}</h1><p>{garageMode==="fleet"?tr("Separate baseline and odometer history for every vehicle.","Atskira pradinė ir odometro istorija kiekvienai priemonei."):tr("Service, inspections and insurance dates before they become problems.","Aptarnavimai, patikros ir draudimo datos prieš joms tampant problema.")}</p></div><Button onClick={()=>garageMode==="fleet"?openEditor("wheel"):(state.wheel.length||state.gear.length)&&openEditor("maintenance")} disabled={garageMode==="maintenance"&&!state.wheel.length&&!state.gear.length}><Plus/>{garageMode==="fleet"?tr("Add vehicle","Pridėti priemonę"):tr("Add task","Pridėti užduotį")}</Button></section><div className="view-switch"><button className={garageMode==="fleet"?"active":""} onClick={()=>setGarageMode("fleet")}><Gauge/>{tr("Fleet","Parkas")}</button><button className={garageMode==="maintenance"?"active":""} onClick={()=>setGarageMode("maintenance")}><Wrench/>{tr("Maintenance","Priežiūra")}{due.length>0&&<span>{due.length}</span>}</button></div>{garageMode==="maintenance"&&<MaintenanceCalendar state={state} actions={actions}/>} {garageMode==="fleet"?(totals.length?<div className="wheel-grid">{totals.map(s=><VehicleCard key={s.wheel.id} wheel={s.wheel} state={state} actions={actions} expanded={focusedWheel===s.wheel.id}/>)}</div>:<div className="panel"><Blank icon={Gauge} title={tr("Add your first vehicle","Pridėk pirmą priemonę")} description={tr("The baseline odometer may be zero. Renaming later will keep all linked records.","Pradinis odometras gali būti nulis. Vėliau pervadinus ryšiai išliks.")}><Button onClick={()=>openEditor("wheel")}><Plus/>{tr("Add vehicle","Pridėti priemonę")}</Button></Blank></div>):(state.maintenance.length?<div className="wheel-grid">{state.maintenance.map(item=><MaintenanceCard key={item.id} item={item} state={state} actions={actions}/>)}</div>:<div className="panel"><Blank icon={Wrench} title={tr("Plan the next check","Suplanuok kitą patikrą")} description={tr("Track tread, bearings, tires, battery health, custom work and insurance expiry.","Sek protektorių, guolius, padangas, bateriją, kitus darbus ir draudimo galiojimą.")}>{state.wheel.length||state.gear.length?<Button onClick={()=>openEditor("maintenance")}><Plus/>{tr("Add maintenance","Pridėti priežiūrą")}</Button>:<p className="field-hint">{tr("Add a vehicle or gear item first.","Pirmiausia pridėk priemonę arba ekipuotę.")}</p>}</Blank></div>)}</TabsContent>

    <TabsContent value="gear"><section className="page-heading"><div><p className="eyebrow">{tr("EVERYTHING THAT RIDES WITH YOU","VISKAS, KAS KELIAUJA KARTU")}</p><h1>{tr("Gear","Ekipuotė")}</h1><p>{tr("From footwear and helmets to action cameras, Cardo and accessories.","Nuo avalynės ir šalmų iki kamerų, Cardo ir kitų priedų.")}</p></div><Button onClick={()=>openEditor("gear")}><Plus/>{tr("Add gear","Pridėti ekipuotę")}</Button></section>{state.gear.length>0&&<div className="toolbar gear-toolbar"><div className="search-field"><Search/><Input aria-label={tr("Search gear","Ieškoti ekipuotės")} placeholder={tr("Search gear…","Ieškoti ekipuotės…")} value={gearSearch} onChange={e=>setGearSearch(e.target.value)}/><Button variant="ghost" size="icon" onClick={()=>sortGear("name")} aria-label={tr("Sort gear by name, reverse direction","Rūšiuoti pagal pavadinimą, keisti kryptį")}>{gearSort==="name"&&gearAsc?<ArrowUp/>:<ArrowDown/>}</Button></div><div className="gear-sort-control"><Pick label={tr("Filter gear category","Filtruoti kategoriją")} value={filterGear} onChange={setFilterGear} options={[{value:"all",label:tr("All categories","Visos kategorijos")},...GEAR_CATEGORIES.map(value=>({value,label:gearCategory(value)}))]}/><Button variant="ghost" size="icon" onClick={()=>sortGear("category")} aria-label={tr("Sort gear by category, reverse direction","Rūšiuoti pagal kategoriją, keisti kryptį")}>{gearSort==="category"&&gearAsc?<ArrowUp/>:<ArrowDown/>}</Button></div><div className="gear-sort-control"><Pick label={tr("Filter gear status","Filtruoti būseną")} value={filterGearStatus} onChange={setFilterGearStatus} options={[{value:"all",label:tr("All statuses","Visos būsenos")},...GEAR_STATUSES.map(value=>({value,label:gearStatus(value)}))]}/><Button variant="ghost" size="icon" onClick={()=>sortGear("status")} aria-label={tr("Sort gear by status, reverse direction","Rūšiuoti pagal būseną, keisti kryptį")}>{gearSort==="status"&&gearAsc?<ArrowUp/>:<ArrowDown/>}</Button></div><span>{visibleGear.length} {tr("of","iš")} {state.gear.length}</span></div>}{visibleGear.length?<div className="wheel-grid gear-grid">{visibleGear.map(gear=><GearCard key={gear.id} gear={gear} state={state} actions={actions}/>)}</div>:<div className="panel"><Blank icon={Backpack} title={state.gear.length?tr("No matching gear","Atitinkančios ekipuotės nėra"):tr("All your gear in one place","Visa tavo ekipuotė vienoje vietoje")} description={state.gear.length?tr("Change the search or clear the filters.","Pakeisk paiešką arba išvalyk filtrus."):tr("Record your equipment, model, size and what it is used with.","Surašyk ekipuotę, modelį, dydį ir kur ji naudojama.")}>{state.gear.length?<Button variant="outline" onClick={()=>{setGearSearch("");setFilterGear("all");setFilterGearStatus("all");}}>{tr("Clear filters","Išvalyti filtrus")}</Button>:<Button onClick={()=>openEditor("gear")}><Plus/>{tr("Add first item","Pridėti pirmą daiktą")}</Button>}</Blank></div>}</TabsContent>

    <TabsContent value="analytics"><section className="page-heading"><div><p className="eyebrow">{tr("EXPLORE YOUR DISTANCE","TYRINĖK SAVO RIDĄ")}</p><h1>{tr("Analytics","Analitika")}</h1><p>{tr("Interactive charts built from your ride and odometer history. Drag the range handles to pan and zoom.","Interaktyvūs grafikai iš važiavimų ir odometro istorijos. Tempk intervalo kraštus masteliui ir laikotarpiui.")}</p></div><Button variant="outline" onClick={()=>setView("rides")}><Route/>{tr("Ride data","Važiavimų duomenys")}</Button></section><AnalyticsView state={state} actions={actions}/></TabsContent>
  </>;
}
