"use client";
import {useState,type ReactNode} from "react";
import {ArrowRight,ArrowUpFromLine,ChevronRight,File,Gauge,Mountain,Paperclip,Pencil,Plus,Route,Trash2,TriangleAlert,Wrench,ArrowDownToLine,Backpack,Camera,Headphones,Shield,Footprints,Shirt,Hand,Cable,Package,Search} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from "@/components/ui/table";
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from "@/components/ui/empty";
import {TabsContent} from "@/components/ui/tabs";
import {Pick,type EditableKind} from "./forms";
import {GEAR_CATEGORIES,GEAR_STATUSES,gearCategoryLabels,gearStatusLabels,formatDate,formatKm,tripStats,wheelStats,type Attachment,type Entity,type Gear,type Kind,type Ride,type State,type Trip} from "@/lib/kairo/domain";
import {driveFileUrl} from "@/lib/kairo/drive";

export type Detail={kind:"trip"|"ride";id:string};
export type View="overview"|"readings"|"rides"|"trips"|"wheels"|"gear";
export type ViewActions={openEditor:(kind:EditableKind,entity?:Entity,tripId?:string)=>void;askDelete:(kind:Kind,entity:Entity)=>void;setDetail:(d:Detail)=>void};
export function Blank({icon:Icon,title,description,children}:{icon:typeof Route;title:string;description:string;children?:ReactNode}){return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><Icon/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>;}
export function SmallActions({edit,remove}:{edit:()=>void;remove:()=>void}){return <div className="row-actions"><Button variant="ghost" size="icon" onClick={edit} aria-label="Redaguoti"><Pencil/></Button><Button variant="ghost" size="icon" onClick={remove} aria-label="Pašalinti"><Trash2/></Button></div>;}
export function RideRow({ride,state,actions}:{ride:Ride;state:State;actions:ViewActions}){
  const wheel=state.wheel.find(w=>w.id===ride.wheelId),trip=state.trip.find(t=>t.id===ride.tripId),count=state.attachment.filter(a=>a.ownerKind==="ride"&&a.ownerId===ride.id).length;
  return <article className="ride-row"><button className="ride-primary" onClick={()=>actions.setDetail({kind:"ride",id:ride.id})}><span className="ride-dot" style={{background:wheel?.color}}><Route/></span><span className="ride-text"><strong>{ride.name}</strong><span>{formatDate(ride.at,true,ride.timeZone)} · {wheel?.name??"Vienaratis nepasiekiamas"}</span>{trip&&<span className="trip-label"><Mountain/>{trip.name}</span>}</span><span className="ride-distance">{formatKm(ride.distanceKm)}<small>km</small>{count>0&&<span className="attachment-count"><Paperclip/>{count}</span>}</span><ChevronRight className="muted"/></button><SmallActions edit={()=>actions.openEditor("ride",ride)} remove={()=>actions.askDelete("ride",ride)}/></article>;
}
export function TripCard({trip,state,actions}:{trip:Trip;state:State;actions:ViewActions}){
  const stats=tripStats(trip,state.ride,state.attachment);
  return <article className="trip-card"><button onClick={()=>actions.setDetail({kind:"trip",id:trip.id})} className="trip-card-main"><div className="trip-card-top"><span className="trip-icon"><Mountain/></span><span className="eyebrow">{stats.days} d.</span><ChevronRight/></div><h3>{trip.name}</h3><p>{formatDate(trip.startDate)} <span>→</span> {formatDate(trip.endDate)}</p><div className="trip-card-stats"><span><strong>{formatKm(stats.distanceKm)}</strong> km{stats.unknownDistances>0?" + ?":""}</span><span>{stats.rides.length} pasivaž.</span><span><Paperclip/>{stats.attachments.length}</span></div></button><div className="trip-card-footer"><span>{trip.notes?trip.notes.slice(0,85):"Kelionės užrašai ir failai"}</span><SmallActions edit={()=>actions.openEditor("trip",trip)} remove={()=>actions.askDelete("trip",trip)}/></div></article>;
}
const bytes=(n:number)=>n<1024?`${n} B`:n<1024*1024?`${(n/1024).toFixed(0)} KB`:`${(n/1024/1024).toFixed(1)} MB`;
const gearIcons={helmet:Shield,footwear:Footprints,protection:Shield,gloves:Hand,clothing:Shirt,camera:Camera,intercom:Headphones,bag:Backpack,charging:Cable,other:Package};
function GearCard({gear,actions}:{gear:Gear;actions:ViewActions}){
  const Icon=gearIcons[gear.category];
  return <article className="gear-card panel"><div className="section-heading"><span className="gear-icon"><Icon/></span><SmallActions edit={()=>actions.openEditor("gear",gear)} remove={()=>actions.askDelete("gear",gear)}/></div><p className="eyebrow">{gearCategoryLabels[gear.category]}</p><h2>{gear.name}</h2><span className={`gear-status gear-status-${gear.status}`}>{gearStatusLabels[gear.status]}</span>{(gear.brand||gear.model||gear.size||gear.purchasedOn)&&<dl>{gear.brand&&<div><dt>Gamintojas</dt><dd>{gear.brand}</dd></div>}{gear.model&&<div><dt>Modelis</dt><dd>{gear.model}</dd></div>}{gear.size&&<div><dt>Dydis</dt><dd>{gear.size}</dd></div>}{gear.purchasedOn&&<div><dt>Įsigyta</dt><dd>{formatDate(gear.purchasedOn)}</dd></div>}</dl>}{gear.notes&&<details className="gear-notes"><summary>Pastabos</summary><p className="preserve-lines">{gear.notes}</p></details>}</article>;
}
export function FileListView({files,localIds,onDownload,onDelete}:{files:Attachment[];localIds:Set<string>;onDownload:(a:Attachment)=>void;onDelete:(a:Attachment)=>void}){return <div className="file-list">{files.map(a=><div className="file-row" key={a.id}><div className="file-badge"><File/><span>{a.name.split(".").at(-1)?.slice(0,5).toUpperCase()}</span></div><div className="file-info"><strong>{a.name}</strong><span>{bytes(a.size)} · {a.driveId?"Google Drive":localIds.has(a.id)?"Tik šiame įrenginyje":"Originalas dar neatsiųstas"}</span></div><div className="row-actions">{a.driveId?<Button variant="outline" size="sm" asChild><a href={driveFileUrl(a.driveId)} target="_blank" rel="noopener noreferrer">Atverti <ArrowRight/></a></Button>:<Button variant="outline" size="icon" disabled={!localIds.has(a.id)} onClick={()=>onDownload(a)} aria-label={`Atsisiųsti ${a.name}`}><ArrowDownToLine/></Button>}<Button variant="ghost" size="icon" aria-label={`Pašalinti nuorodą ${a.name}`} onClick={()=>onDelete(a)}><Trash2/></Button></div></div>)}</div>;}

export function MainViews({state,actions,setView,openStorage}:{state:State;actions:ViewActions;setView:(v:View)=>void;openStorage:()=>void}){
  const [filterWheel,setFilterWheel]=useState("all");
  const [filterGear,setFilterGear]=useState("all"),[filterGearStatus,setFilterGearStatus]=useState("all"),[gearSearch,setGearSearch]=useState("");
  const search=gearSearch.trim().toLocaleLowerCase("lt");
  const visibleGear=state.gear.filter(g=>(filterGear==="all"||g.category===filterGear)&&(filterGearStatus==="all"||g.status===filterGearStatus)&&[g.name,g.brand,g.model,g.size,g.notes,gearCategoryLabels[g.category]].join(" ").toLocaleLowerCase("lt").includes(search));
  const {openEditor,askDelete}=actions;
  const totals=state.wheel.map(w=>({wheel:w,...wheelStats(w,state.reading)}));
  const totalKm=totals.some(s=>s.trackedKm===null)?null:totals.reduce((n,s)=>n+(s.trackedKm??0),0);
  const warnings=totals.reduce((n,s)=>n+s.warnings,0);
  return <>
    <TabsContent value="overview"><section className="page-heading"><div><p className="eyebrow">MANO ARCHYVAS</p><h1>Gera vėl riedėti.</h1><p>Kasdieniai kilometrai ir kelionės, kurias norisi prisiminti.</p></div><Button onClick={()=>state.wheel.length?openEditor("reading"):openEditor("wheel")}><Plus/>{state.wheel.length?"Pridėti rodmenį":"Pridėti vienaratį"}</Button></section>
      <div className="stats-grid"><article className="stat primary-stat"><span><Gauge/>Užfiksuota rida</span><div>{formatKm(totalKm)}<small>km</small></div><p>Nuo pradinių odometro rodmenų</p></article><article className="stat"><span><Route/>Pasivažinėjimai</span><div>{state.ride.length}<small>įrašų</small></div><p>Atskiri pasivažinėjimai ir kelionių etapai</p></article><article className="stat"><span><Mountain/>Kelionės</span><div>{state.trip.length}<small>kelionių</small></div><p>Nuo vienos dienos iki ilgo nuotykio</p></article></div>
      {!state.wheel.length&&!state.trip.length&&<section className="start-panel"><div><span className="eyebrow">PRADĖK NUO SAVO DUOMENŲ</span><h2>Archyvas prasideda čia.</h2><p>Pridėk vienaratį ir jo pradinį odometrą arba perkelk dabartinės PWA Excel įrašus. Keliones gali kurti iš karto.</p></div><div className="start-actions"><Button onClick={()=>openEditor("wheel")}><Plus/>Pridėti vienaratį</Button><Button variant="outline" onClick={openStorage}><ArrowUpFromLine/>Importuoti duomenis</Button></div></section>}
      {warnings>0&&<div className="notice warning"><TriangleAlert/><span>{warnings} odometro rodmenis reikia patikrinti. Jie pažymėti odometro lentelėje.</span><Button variant="ghost" size="sm" onClick={()=>setView("readings")}>Peržiūrėti</Button></div>}
      <div className="overview-columns"><section className="panel"><div className="section-heading"><h2>Mano vienaračiai</h2><Button variant="ghost" size="sm" onClick={()=>setView("wheels")}>Garažas <ArrowRight/></Button></div>{totals.length?totals.map(s=><div className="wheel-summary" key={s.wheel.id}><span className="wheel-symbol" style={{color:s.wheel.color}}><Gauge/></span><div><strong>{s.wheel.name}</strong><p>{s.lastAt?`Atnaujinta ${formatDate(s.lastAt)}`:"Tik pradinis rodmuo"}</p></div><div className="wheel-reading"><strong>{formatKm(s.odometerKm)}</strong><small>km odometras</small></div></div>):<Blank icon={Gauge} title="Garažas dar tuščias" description="Kiekvieno vienaračio odometro istorija bus atskira."/>}</section><section className="panel quick-panel"><span className="eyebrow">GREITAS ĮRAŠAS</span><h2>Ką šiandien išsaugosi?</h2><button onClick={()=>state.wheel.length?openEditor("ride"):openEditor("wheel")}><Route/><span><strong>Pasivažinėjimą</strong><small>Maršrutas, įspūdžiai ir failai</small></span><Plus/></button><button onClick={()=>openEditor("trip")}><Mountain/><span><strong>Kelionę</strong><small>Kelios dienos, vienas archyvas</small></span><Plus/></button></section></div>
      <section className="section"><div className="section-heading"><div><p className="eyebrow">DAUGIAU NEI KILOMETRAI</p><h2>Naujausios kelionės</h2></div><Button variant="outline" onClick={()=>openEditor("trip")}><Plus/>Nauja kelionė</Button></div>{state.trip.length?<div className="trip-grid">{state.trip.slice(0,3).map(t=><TripCard key={t.id} trip={t} state={state} actions={actions}/>)}</div>:<div className="trip-empty"><Mountain/><div><h3>Vieta tavo kitai kelionei.</h3><p>Sujunk dienų pasivažinėjimus, GPX, logus, nuotraukas ir vaizdo įrašus.</p></div><Button variant="ghost" onClick={()=>openEditor("trip")}>Sukurti kelionę <ArrowRight/></Button></div>}</section>
    </TabsContent>
    <TabsContent value="readings"><section className="page-heading"><div><p className="eyebrow">KILOMETRŲ ISTORIJA</p><h1>Odometras</h1><p>Rodmenys yra faktai. Atstumai tarp jų perskaičiuojami automatiškai.</p></div><Button onClick={()=>state.wheel.length?openEditor("reading"):openEditor("wheel")}><Plus/>Pridėti rodmenį</Button></section><div className="toolbar"><Pick label="Filtruoti vienaratį" value={filterWheel} onChange={setFilterWheel} options={[{value:"all",label:"Visi vienaračiai"},...state.wheel.map(w=>({value:w.id,label:w.name}))]}/><span>{state.reading.length} rodmenų · intervalas nebūtinai yra vienas pasivažinėjimas</span></div>
    {!state.reading.length?<div className="panel"><Blank icon={Gauge} title="Dar nėra odometro rodmenų" description="Įvesk vienaračio odometro rodmenį arba importuok dabartinės PWA Excel istoriją."><Button variant="outline" onClick={openStorage}><ArrowUpFromLine/>Importuoti</Button></Blank></div>:<div className="panel data-panel"><Table><TableHeader><TableRow><TableHead>Data ir laikas</TableHead><TableHead>Vienaratis</TableHead><TableHead className="number-cell">Odometras</TableHead><TableHead className="number-cell">Nuo ankstesnio</TableHead><TableHead>Pastabos</TableHead><TableHead><span className="sr-only">Veiksmai</span></TableHead></TableRow></TableHeader><TableBody>{totals.flatMap(s=>s.intervals.map(i=>({...i,wheel:s.wheel}))).filter(r=>filterWheel==="all"||r.wheel.id===filterWheel).sort((a,b)=>b.reading.at.localeCompare(a.reading.at)).map(i=><TableRow key={i.reading.id} className={i.warning?"warning-row":""}><TableCell><strong className="date-cell">{formatDate(i.reading.at,true)}</strong>{i.warning&&<span className="row-warning"><TriangleAlert/>{i.warning}</span>}</TableCell><TableCell><span className="wheel-chip"><i style={{background:i.wheel.color}}/>{i.wheel.name}</span></TableCell><TableCell className="number-cell"><strong>{formatKm(i.reading.odometerKm)}</strong><small> km</small></TableCell><TableCell className="number-cell">{formatKm(i.distance)}<small> km</small></TableCell><TableCell className="notes-cell">{i.reading.notes||"—"}</TableCell><TableCell><SmallActions edit={()=>openEditor("reading",i.reading)} remove={()=>askDelete("reading",i.reading)}/></TableCell></TableRow>)}</TableBody></Table></div>}</TabsContent>
    <TabsContent value="rides"><section className="page-heading"><div><p className="eyebrow">PO VIENĄ IŠVAŽIAVIMĄ</p><h1>Pasivažinėjimai</h1><p>Trumpas ratas po miestą arba vienas ilgesnės kelionės etapas.</p></div><Button onClick={()=>state.wheel.length?openEditor("ride"):openEditor("wheel")}><Plus/>Naujas pasivažinėjimas</Button></section><div className="panel">{state.ride.length?state.ride.map(r=><RideRow key={r.id} ride={r} state={state} actions={actions}/>):<Blank icon={Route} title="Pirmas pasivažinėjimas laukia" description="Pavadink pasivažinėjimą, pasirink vienaratį ir, jei nori, priskirk kelionei. Failus prisegsi jo viduje."><Button onClick={()=>state.wheel.length?openEditor("ride"):openEditor("wheel")}><Plus/>Pradėti</Button></Blank>}</div></TabsContent>
    <TabsContent value="trips"><section className="page-heading"><div><p className="eyebrow">KELIOS DIENOS. VIENA ISTORIJA.</p><h1>Kelionės</h1><p>Pasivažinėjimai, prisiminimai ir originalūs failai vienoje vietoje.</p></div><Button onClick={()=>openEditor("trip")}><Plus/>Nauja kelionė</Button></section>{state.trip.length?<div className="trip-grid">{state.trip.map(t=><TripCard key={t.id} trip={t} state={state} actions={actions}/>)}</div>:<div className="panel"><Blank icon={Mountain} title="Kur norėtum išvažiuoti?" description="Sukurk kelionę su pradžios ir pabaigos data. Ji gali trukti vieną dieną, savaitgalį ar kelias savaites."><Button onClick={()=>openEditor("trip")}><Plus/>Sukurti kelionę</Button></Blank></div>}</TabsContent>
    <TabsContent value="wheels"><section className="page-heading"><div><p className="eyebrow">KIEKVIENAS TURI SAVO ISTORIJĄ</p><h1>Garažas</h1><p>Atskiri pradiniai rodmenys, atskiros odometro sekos.</p></div><Button onClick={()=>openEditor("wheel")}><Plus/>Pridėti vienaratį</Button></section>{totals.length?<div className="wheel-grid">{totals.map(s=><article className="wheel-card panel" key={s.wheel.id}><div className="section-heading"><span className="wheel-symbol" style={{color:s.wheel.color}}><Gauge/></span><SmallActions edit={()=>openEditor("wheel",s.wheel)} remove={()=>askDelete("wheel",s.wheel)}/></div><h2>{s.wheel.name}</h2><div className="odometer">{formatKm(s.odometerKm)}<span>km</span></div><dl><div><dt>Užfiksuota rida</dt><dd>{formatKm(s.trackedKm)} km</dd></div><div><dt>Pradinis odometras</dt><dd>{formatKm(s.wheel.baselineKm)} km</dd></div><div><dt>Istorijos pradžia</dt><dd>{formatDate(s.wheel.baselineDate)}</dd></div><div><dt>Rodmenų</dt><dd>{s.intervals.length}</dd></div></dl>{s.wheel.notes&&<p className="preserve-lines">{s.wheel.notes}</p>}</article>)}</div>:<div className="panel"><Blank icon={Wrench} title="Pridėk savo vienaratį" description="Pradinis odometras gali būti ir nulis. Pavadinimą vėliau galėsi keisti neprarasdamas susietų įrašų."><Button onClick={()=>openEditor("wheel")}><Plus/>Pridėti vienaratį</Button></Blank></div>}</TabsContent>
    <TabsContent value="gear"><section className="page-heading"><div><p className="eyebrow">VISKAS, KAS KELIAUJA KARTU</p><h1>Ekipuotė</h1><p>Nuo avalynės ir šalmo iki veiksmo kameros, Cardo ir kitų priedų.</p></div><Button onClick={()=>openEditor("gear")}><Plus/>Pridėti ekipuotę</Button></section>{state.gear.length>0&&<div className="toolbar gear-toolbar"><div className="search-field"><Search/><Input aria-label="Ieškoti ekipuotės" placeholder="Ieškoti ekipuotės…" value={gearSearch} onChange={e=>setGearSearch(e.target.value)}/></div><Pick label="Filtruoti ekipuotės kategoriją" value={filterGear} onChange={setFilterGear} options={[{value:"all",label:"Visos kategorijos"},...GEAR_CATEGORIES.map(value=>({value,label:gearCategoryLabels[value]}))]}/><Pick label="Filtruoti ekipuotės būseną" value={filterGearStatus} onChange={setFilterGearStatus} options={[{value:"all",label:"Visos būsenos"},...GEAR_STATUSES.map(value=>({value,label:gearStatusLabels[value]}))]}/><span>{visibleGear.length} iš {state.gear.length} įrašų</span></div>}{visibleGear.length?<div className="wheel-grid">{visibleGear.map(gear=><GearCard key={gear.id} gear={gear} actions={actions}/>)}</div>:<div className="panel"><Blank icon={Backpack} title={state.gear.length?"Atitinkančios ekipuotės nėra":"Tavo ekipuotė vienoje vietoje"} description={state.gear.length?"Pakeisk paiešką arba išvalyk filtrus.":"Surašyk turimus daiktus, jų dydžius, modelius ir pastabas. Įrašai bus saugomi kartu su tavo rida ir kelionėmis."}>{state.gear.length?<Button variant="outline" onClick={()=>{setGearSearch("");setFilterGear("all");setFilterGearStatus("all");}}>Išvalyti filtrus</Button>:<Button onClick={()=>openEditor("gear")}><Plus/>Pridėti pirmą daiktą</Button>}</Blank></div>}</TabsContent>
  </>;
}
